'use client';

import React, { useState, useMemo } from 'react';
import { MagnifyingGlassIcon, XIcon } from '@phosphor-icons/react';

type EmojiItem = {
    emoji: string;
    name: string;
    category: string;
    keywords: string[];
};

type EmojiCatalogueProps = {
    onSelectEmoji: (emoji: string) => void;
    onClose: () => void;
    isOpen: boolean;
};

// Comprehensive emoji data organized by categories
const EMOJI_DATA: EmojiItem[] = [
    // Faces & People
    { emoji: '😀', name: 'grinning face', category: 'Faces & People', keywords: ['grinning', 'face', 'smile', 'happy'] },
    { emoji: '😃', name: 'grinning face with big eyes', category: 'Faces & People', keywords: ['grinning', 'face', 'happy', 'joy'] },
    { emoji: '😄', name: 'grinning face with smiling eyes', category: 'Faces & People', keywords: ['grinning', 'face', 'happy', 'joy', 'laugh'] },
    { emoji: '😁', name: 'beaming face with smiling eyes', category: 'Faces & People', keywords: ['grinning', 'face', 'happy', 'smile', 'joy'] },
    { emoji: '😆', name: 'grinning squinting face', category: 'Faces & People', keywords: ['grinning', 'face', 'happy', 'laugh', 'satisfied'] },
    { emoji: '😅', name: 'grinning face with sweat', category: 'Faces & People', keywords: ['grinning', 'face', 'happy', 'laugh', 'sweat'] },
    { emoji: '🤣', name: 'rolling on the floor laughing', category: 'Faces & People', keywords: ['rofl', 'laughing', 'lol', 'happy'] },
    { emoji: '😂', name: 'face with tears of joy', category: 'Faces & People', keywords: ['laughing', 'happy', 'tears', 'joy'] },
    { emoji: '🙂', name: 'slightly smiling face', category: 'Faces & People', keywords: ['smile', 'happy', 'face'] },
    { emoji: '🙃', name: 'upside-down face', category: 'Faces & People', keywords: ['upside-down', 'face', 'silly'] },
    { emoji: '😉', name: 'winking face', category: 'Faces & People', keywords: ['wink', 'face', 'flirt'] },
    { emoji: '😊', name: 'smiling face with smiling eyes', category: 'Faces & People', keywords: ['smile', 'happy', 'face', 'blush'] },
    { emoji: '😇', name: 'smiling face with halo', category: 'Faces & People', keywords: ['angel', 'halo', 'innocent'] },
    { emoji: '🥰', name: 'smiling face with hearts', category: 'Faces & People', keywords: ['love', 'hearts', 'adore'] },
    { emoji: '😍', name: 'smiling face with heart-eyes', category: 'Faces & People', keywords: ['love', 'heart', 'eyes', 'adore'] },
    { emoji: '🤩', name: 'star-struck', category: 'Faces & People', keywords: ['star', 'struck', 'eyes', 'grinning'] },
    { emoji: '😘', name: 'face blowing a kiss', category: 'Faces & People', keywords: ['kiss', 'love', 'face'] },
    { emoji: '😗', name: 'kissing face', category: 'Faces & People', keywords: ['kiss', 'love', 'face'] },
    { emoji: '☺️', name: 'smiling face', category: 'Faces & People', keywords: ['smile', 'happy', 'face'] },
    { emoji: '😚', name: 'kissing face with closed eyes', category: 'Faces & People', keywords: ['kiss', 'love', 'closed', 'eyes'] },
    { emoji: '😙', name: 'kissing face with smiling eyes', category: 'Faces & People', keywords: ['kiss', 'love', 'smile', 'eyes'] },
    { emoji: '🥲', name: 'smiling face with tear', category: 'Faces & People', keywords: ['smile', 'tear', 'cry', 'happy'] },
    { emoji: '😋', name: 'face savoring food', category: 'Faces & People', keywords: ['savoring', 'food', 'tongue', 'delicious'] },
    { emoji: '😛', name: 'face with tongue', category: 'Faces & People', keywords: ['tongue', 'face', 'silly'] },
    { emoji: '😜', name: 'winking face with tongue', category: 'Faces & People', keywords: ['wink', 'tongue', 'silly', 'crazy'] },
    { emoji: '🤪', name: 'zany face', category: 'Faces & People', keywords: ['zany', 'face', 'crazy', 'tongue'] },
    { emoji: '😝', name: 'squinting face with tongue', category: 'Faces & People', keywords: ['tongue', 'silly', 'squint'] },
    { emoji: '🤑', name: 'money-mouth face', category: 'Faces & People', keywords: ['money', 'dollar', 'face'] },
    { emoji: '🤗', name: 'hugging face', category: 'Faces & People', keywords: ['hugging', 'face', 'hug'] },
    { emoji: '🤭', name: 'face with hand over mouth', category: 'Faces & People', keywords: ['face', 'hand', 'mouth', 'quiet'] },
    { emoji: '🤫', name: 'shushing face', category: 'Faces & People', keywords: ['shush', 'quiet', 'face'] },
    { emoji: '🤔', name: 'thinking face', category: 'Faces & People', keywords: ['thinking', 'face', 'consider'] },
    { emoji: '🤐', name: 'zipper-mouth face', category: 'Faces & People', keywords: ['zipper', 'mouth', 'quiet', 'secret'] },
    { emoji: '🤨', name: 'face with raised eyebrow', category: 'Faces & People', keywords: ['eyebrow', 'face', 'suspicious'] },
    { emoji: '😐', name: 'neutral face', category: 'Faces & People', keywords: ['neutral', 'face', 'meh'] },
    { emoji: '😑', name: 'expressionless face', category: 'Faces & People', keywords: ['expressionless', 'face', 'blank'] },
    { emoji: '😶', name: 'face without mouth', category: 'Faces & People', keywords: ['face', 'mouth', 'quiet', 'silent'] },
    { emoji: '😏', name: 'smirking face', category: 'Faces & People', keywords: ['smirk', 'face', 'sly'] },
    { emoji: '😒', name: 'unamused face', category: 'Faces & People', keywords: ['unamused', 'face', 'unhappy'] },
    { emoji: '🙄', name: 'face with rolling eyes', category: 'Faces & People', keywords: ['rolling', 'eyes', 'face'] },
    { emoji: '😬', name: 'grimacing face', category: 'Faces & People', keywords: ['grimace', 'face', 'awkward'] },
    { emoji: '🤥', name: 'lying face', category: 'Faces & People', keywords: ['lying', 'face', 'pinocchio'] },
    { emoji: '😔', name: 'pensive face', category: 'Faces & People', keywords: ['pensive', 'face', 'sad', 'depressed'] },
    { emoji: '😕', name: 'confused face', category: 'Faces & People', keywords: ['confused', 'face', 'worried'] },
    { emoji: '🙁', name: 'slightly frowning face', category: 'Faces & People', keywords: ['frown', 'face', 'sad'] },
    { emoji: '☹️', name: 'frowning face', category: 'Faces & People', keywords: ['frown', 'face', 'sad'] },
    { emoji: '😣', name: 'persevering face', category: 'Faces & People', keywords: ['persevere', 'face', 'struggling'] },
    { emoji: '😖', name: 'confounded face', category: 'Faces & People', keywords: ['confounded', 'face', 'confused'] },
    { emoji: '😫', name: 'tired face', category: 'Faces & People', keywords: ['tired', 'face', 'exhausted'] },
    { emoji: '😩', name: 'weary face', category: 'Faces & People', keywords: ['weary', 'face', 'tired'] },
    { emoji: '🥺', name: 'pleading face', category: 'Faces & People', keywords: ['pleading', 'face', 'puppy', 'eyes'] },
    { emoji: '😢', name: 'crying face', category: 'Faces & People', keywords: ['crying', 'face', 'sad', 'tear'] },
    { emoji: '😭', name: 'loudly crying face', category: 'Faces & People', keywords: ['crying', 'face', 'sad', 'tears'] },
    { emoji: '😤', name: 'face with steam from nose', category: 'Faces & People', keywords: ['steam', 'nose', 'face', 'angry'] },
    { emoji: '😠', name: 'angry face', category: 'Faces & People', keywords: ['angry', 'face', 'mad'] },
    { emoji: '😡', name: 'pouting face', category: 'Faces & People', keywords: ['pouting', 'face', 'angry', 'red'] },
    { emoji: '🤬', name: 'face with symbols on mouth', category: 'Faces & People', keywords: ['swearing', 'cursing', 'face', 'angry'] },
    { emoji: '🤯', name: 'exploding head', category: 'Faces & People', keywords: ['exploding', 'head', 'mind', 'blown'] },
    { emoji: '😳', name: 'flushed face', category: 'Faces & People', keywords: ['flushed', 'face', 'embarrassed'] },
    { emoji: '🥵', name: 'hot face', category: 'Faces & People', keywords: ['hot', 'face', 'heat', 'sweating'] },
    { emoji: '🥶', name: 'cold face', category: 'Faces & People', keywords: ['cold', 'face', 'freezing', 'blue'] },
    { emoji: '😱', name: 'face screaming in fear', category: 'Faces & People', keywords: ['screaming', 'face', 'fear', 'scared'] },
    { emoji: '😨', name: 'fearful face', category: 'Faces & People', keywords: ['fearful', 'face', 'scared', 'surprised'] },
    { emoji: '😰', name: 'anxious face with sweat', category: 'Faces & People', keywords: ['anxious', 'face', 'sweat', 'worried'] },
    { emoji: '😥', name: 'sad but relieved face', category: 'Faces & People', keywords: ['sad', 'relieved', 'face', 'sweat'] },
    { emoji: '😓', name: 'downcast face with sweat', category: 'Faces & People', keywords: ['downcast', 'face', 'sweat', 'sad'] },
    { emoji: '🤗', name: 'hugging face', category: 'Faces & People', keywords: ['hugging', 'face', 'hug'] },
    { emoji: '🥱', name: 'yawning face', category: 'Faces & People', keywords: ['yawning', 'face', 'tired', 'sleepy'] },
    { emoji: '😴', name: 'sleeping face', category: 'Faces & People', keywords: ['sleeping', 'face', 'tired', 'sleep'] },
    { emoji: '😪', name: 'sleepy face', category: 'Faces & People', keywords: ['sleepy', 'face', 'tired', 'sleep'] },

    // Animals & Nature
    { emoji: '🐶', name: 'dog face', category: 'Animals & Nature', keywords: ['dog', 'face', 'pet', 'animal'] },
    { emoji: '🐱', name: 'cat face', category: 'Animals & Nature', keywords: ['cat', 'face', 'pet', 'animal'] },
    { emoji: '🐭', name: 'mouse face', category: 'Animals & Nature', keywords: ['mouse', 'face', 'animal'] },
    { emoji: '🐹', name: 'hamster face', category: 'Animals & Nature', keywords: ['hamster', 'face', 'pet', 'animal'] },
    { emoji: '🐰', name: 'rabbit face', category: 'Animals & Nature', keywords: ['rabbit', 'face', 'bunny', 'animal'] },
    { emoji: '🦊', name: 'fox face', category: 'Animals & Nature', keywords: ['fox', 'face', 'animal'] },
    { emoji: '🐻', name: 'bear face', category: 'Animals & Nature', keywords: ['bear', 'face', 'animal'] },
    { emoji: '🐼', name: 'panda face', category: 'Animals & Nature', keywords: ['panda', 'face', 'animal', 'bear'] },
    { emoji: '🐨', name: 'koala', category: 'Animals & Nature', keywords: ['koala', 'animal', 'bear'] },
    { emoji: '🐯', name: 'tiger face', category: 'Animals & Nature', keywords: ['tiger', 'face', 'animal', 'cat'] },
    { emoji: '🦁', name: 'lion face', category: 'Animals & Nature', keywords: ['lion', 'face', 'animal', 'cat'] },
    { emoji: '🐮', name: 'cow face', category: 'Animals & Nature', keywords: ['cow', 'face', 'animal', 'beef'] },
    { emoji: '🐷', name: 'pig face', category: 'Animals & Nature', keywords: ['pig', 'face', 'animal'] },
    { emoji: '🐸', name: 'frog face', category: 'Animals & Nature', keywords: ['frog', 'face', 'animal', 'amphibian'] },
    { emoji: '🐵', name: 'monkey face', category: 'Animals & Nature', keywords: ['monkey', 'face', 'animal', 'primate'] },
    { emoji: '🙈', name: 'see-no-evil monkey', category: 'Animals & Nature', keywords: ['monkey', 'see', 'evil', 'animal'] },
    { emoji: '🙉', name: 'hear-no-evil monkey', category: 'Animals & Nature', keywords: ['monkey', 'hear', 'evil', 'animal'] },
    { emoji: '🙊', name: 'speak-no-evil monkey', category: 'Animals & Nature', keywords: ['monkey', 'speak', 'evil', 'animal'] },
    { emoji: '🐔', name: 'chicken', category: 'Animals & Nature', keywords: ['chicken', 'animal', 'bird'] },
    { emoji: '🐧', name: 'penguin', category: 'Animals & Nature', keywords: ['penguin', 'animal', 'bird'] },
    { emoji: '🐦', name: 'bird', category: 'Animals & Nature', keywords: ['bird', 'animal'] },
    { emoji: '🐤', name: 'baby chick', category: 'Animals & Nature', keywords: ['baby', 'chick', 'bird', 'animal'] },
    { emoji: '🐣', name: 'hatching chick', category: 'Animals & Nature', keywords: ['hatching', 'chick', 'bird', 'animal'] },
    { emoji: '🐥', name: 'front-facing baby chick', category: 'Animals & Nature', keywords: ['baby', 'chick', 'bird', 'animal'] },
    { emoji: '🦆', name: 'duck', category: 'Animals & Nature', keywords: ['duck', 'animal', 'bird'] },
    { emoji: '🦅', name: 'eagle', category: 'Animals & Nature', keywords: ['eagle', 'animal', 'bird'] },
    { emoji: '🦉', name: 'owl', category: 'Animals & Nature', keywords: ['owl', 'animal', 'bird'] },
    { emoji: '🦇', name: 'bat', category: 'Animals & Nature', keywords: ['bat', 'animal', 'vampire'] },
    { emoji: '🐺', name: 'wolf face', category: 'Animals & Nature', keywords: ['wolf', 'face', 'animal'] },
    { emoji: '🐗', name: 'boar', category: 'Animals & Nature', keywords: ['boar', 'animal', 'pig'] },
    { emoji: '🐴', name: 'horse face', category: 'Animals & Nature', keywords: ['horse', 'face', 'animal'] },
    { emoji: '🦄', name: 'unicorn face', category: 'Animals & Nature', keywords: ['unicorn', 'face', 'animal', 'mythical'] },
    { emoji: '🐝', name: 'honeybee', category: 'Animals & Nature', keywords: ['bee', 'honeybee', 'insect'] },
    { emoji: '🐛', name: 'bug', category: 'Animals & Nature', keywords: ['bug', 'insect'] },
    { emoji: '🦋', name: 'butterfly', category: 'Animals & Nature', keywords: ['butterfly', 'insect', 'beautiful'] },
    { emoji: '🐌', name: 'snail', category: 'Animals & Nature', keywords: ['snail', 'animal', 'slow'] },
    { emoji: '🐞', name: 'lady beetle', category: 'Animals & Nature', keywords: ['ladybug', 'beetle', 'insect'] },
    { emoji: '🐜', name: 'ant', category: 'Animals & Nature', keywords: ['ant', 'insect'] },
    { emoji: '🕷️', name: 'spider', category: 'Animals & Nature', keywords: ['spider', 'insect'] },
    { emoji: '🦟', name: 'mosquito', category: 'Animals & Nature', keywords: ['mosquito', 'insect', 'bite'] },
    { emoji: '🐢', name: 'turtle', category: 'Animals & Nature', keywords: ['turtle', 'animal', 'slow'] },
    { emoji: '🐍', name: 'snake', category: 'Animals & Nature', keywords: ['snake', 'animal', 'reptile'] },
    { emoji: '🦎', name: 'lizard', category: 'Animals & Nature', keywords: ['lizard', 'animal', 'reptile'] },
    { emoji: '🐙', name: 'octopus', category: 'Animals & Nature', keywords: ['octopus', 'animal', 'sea'] },
    { emoji: '🦑', name: 'squid', category: 'Animals & Nature', keywords: ['squid', 'animal', 'sea'] },
    { emoji: '🦐', name: 'shrimp', category: 'Animals & Nature', keywords: ['shrimp', 'animal', 'sea'] },
    { emoji: '🦞', name: 'lobster', category: 'Animals & Nature', keywords: ['lobster', 'animal', 'sea'] },
    { emoji: '🦀', name: 'crab', category: 'Animals & Nature', keywords: ['crab', 'animal', 'sea'] },
    { emoji: '🐡', name: 'blowfish', category: 'Animals & Nature', keywords: ['blowfish', 'fish', 'animal', 'sea'] },
    { emoji: '🐠', name: 'tropical fish', category: 'Animals & Nature', keywords: ['tropical', 'fish', 'animal', 'sea'] },
    { emoji: '🐟', name: 'fish', category: 'Animals & Nature', keywords: ['fish', 'animal', 'sea'] },
    { emoji: '🐬', name: 'dolphin', category: 'Animals & Nature', keywords: ['dolphin', 'animal', 'sea'] },
    { emoji: '🐳', name: 'spouting whale', category: 'Animals & Nature', keywords: ['whale', 'animal', 'sea'] },
    { emoji: '🐋', name: 'whale', category: 'Animals & Nature', keywords: ['whale', 'animal', 'sea'] },
    { emoji: '🦈', name: 'shark', category: 'Animals & Nature', keywords: ['shark', 'animal', 'sea'] },
    { emoji: '🌸', name: 'cherry blossom', category: 'Animals & Nature', keywords: ['cherry', 'blossom', 'flower', 'spring'] },
    { emoji: '🌺', name: 'hibiscus', category: 'Animals & Nature', keywords: ['hibiscus', 'flower'] },
    { emoji: '🌻', name: 'sunflower', category: 'Animals & Nature', keywords: ['sunflower', 'flower', 'yellow'] },
    { emoji: '🌹', name: 'rose', category: 'Animals & Nature', keywords: ['rose', 'flower', 'love'] },
    { emoji: '🌷', name: 'tulip', category: 'Animals & Nature', keywords: ['tulip', 'flower'] },
    { emoji: '🌿', name: 'herb', category: 'Animals & Nature', keywords: ['herb', 'plant', 'leaf'] },
    { emoji: '🍀', name: 'four leaf clover', category: 'Animals & Nature', keywords: ['clover', 'lucky', 'four', 'leaf'] },
    { emoji: '🌵', name: 'cactus', category: 'Animals & Nature', keywords: ['cactus', 'plant', 'desert'] },
    { emoji: '🌲', name: 'evergreen tree', category: 'Animals & Nature', keywords: ['evergreen', 'tree', 'plant'] },
    { emoji: '🌳', name: 'deciduous tree', category: 'Animals & Nature', keywords: ['deciduous', 'tree', 'plant'] },
    { emoji: '🌴', name: 'palm tree', category: 'Animals & Nature', keywords: ['palm', 'tree', 'plant', 'tropical'] },

    // Food & Drink
    { emoji: '🍎', name: 'red apple', category: 'Food & Drink', keywords: ['apple', 'red', 'fruit'] },
    { emoji: '🍊', name: 'tangerine', category: 'Food & Drink', keywords: ['tangerine', 'orange', 'fruit'] },
    { emoji: '🍋', name: 'lemon', category: 'Food & Drink', keywords: ['lemon', 'fruit', 'sour'] },
    { emoji: '🍌', name: 'banana', category: 'Food & Drink', keywords: ['banana', 'fruit', 'yellow'] },
    { emoji: '🍉', name: 'watermelon', category: 'Food & Drink', keywords: ['watermelon', 'fruit', 'summer'] },
    { emoji: '🍇', name: 'grapes', category: 'Food & Drink', keywords: ['grapes', 'fruit', 'wine'] },
    { emoji: '🍓', name: 'strawberry', category: 'Food & Drink', keywords: ['strawberry', 'fruit', 'red'] },
    { emoji: '🫐', name: 'blueberries', category: 'Food & Drink', keywords: ['blueberries', 'fruit', 'blue'] },
    { emoji: '🍈', name: 'melon', category: 'Food & Drink', keywords: ['melon', 'fruit'] },
    { emoji: '🍒', name: 'cherries', category: 'Food & Drink', keywords: ['cherries', 'fruit', 'red'] },
    { emoji: '🍑', name: 'peach', category: 'Food & Drink', keywords: ['peach', 'fruit'] },
    { emoji: '🥭', name: 'mango', category: 'Food & Drink', keywords: ['mango', 'fruit', 'tropical'] },
    { emoji: '🍍', name: 'pineapple', category: 'Food & Drink', keywords: ['pineapple', 'fruit', 'tropical'] },
    { emoji: '🥥', name: 'coconut', category: 'Food & Drink', keywords: ['coconut', 'fruit', 'tropical'] },
    { emoji: '🥝', name: 'kiwi fruit', category: 'Food & Drink', keywords: ['kiwi', 'fruit', 'green'] },
    { emoji: '🍅', name: 'tomato', category: 'Food & Drink', keywords: ['tomato', 'vegetable', 'red'] },
    { emoji: '🍆', name: 'eggplant', category: 'Food & Drink', keywords: ['eggplant', 'vegetable', 'purple'] },
    { emoji: '🥑', name: 'avocado', category: 'Food & Drink', keywords: ['avocado', 'fruit', 'green'] },
    { emoji: '🥦', name: 'broccoli', category: 'Food & Drink', keywords: ['broccoli', 'vegetable', 'green'] },
    { emoji: '🥬', name: 'leafy greens', category: 'Food & Drink', keywords: ['leafy', 'greens', 'vegetable', 'lettuce'] },
    { emoji: '🥒', name: 'cucumber', category: 'Food & Drink', keywords: ['cucumber', 'vegetable', 'green'] },
    { emoji: '🌶️', name: 'hot pepper', category: 'Food & Drink', keywords: ['hot', 'pepper', 'spicy', 'chili'] },
    { emoji: '🌽', name: 'ear of corn', category: 'Food & Drink', keywords: ['corn', 'vegetable', 'yellow'] },
    { emoji: '🥕', name: 'carrot', category: 'Food & Drink', keywords: ['carrot', 'vegetable', 'orange'] },
    { emoji: '🧄', name: 'garlic', category: 'Food & Drink', keywords: ['garlic', 'vegetable'] },
    { emoji: '🧅', name: 'onion', category: 'Food & Drink', keywords: ['onion', 'vegetable'] },
    { emoji: '🥔', name: 'potato', category: 'Food & Drink', keywords: ['potato', 'vegetable'] },
    { emoji: '🍠', name: 'roasted sweet potato', category: 'Food & Drink', keywords: ['sweet', 'potato', 'vegetable'] },
    { emoji: '🍞', name: 'bread', category: 'Food & Drink', keywords: ['bread', 'loaf'] },
    { emoji: '🥖', name: 'baguette bread', category: 'Food & Drink', keywords: ['baguette', 'bread', 'french'] },
    { emoji: '🥨', name: 'pretzel', category: 'Food & Drink', keywords: ['pretzel', 'snack'] },
    { emoji: '🥯', name: 'bagel', category: 'Food & Drink', keywords: ['bagel', 'bread'] },
    { emoji: '🥞', name: 'pancakes', category: 'Food & Drink', keywords: ['pancakes', 'breakfast'] },
    { emoji: '🧇', name: 'waffle', category: 'Food & Drink', keywords: ['waffle', 'breakfast'] },
    { emoji: '🧀', name: 'cheese wedge', category: 'Food & Drink', keywords: ['cheese', 'dairy'] },
    { emoji: '🍖', name: 'meat on bone', category: 'Food & Drink', keywords: ['meat', 'bone'] },
    { emoji: '🍗', name: 'poultry leg', category: 'Food & Drink', keywords: ['poultry', 'leg', 'chicken'] },
    { emoji: '🥩', name: 'cut of meat', category: 'Food & Drink', keywords: ['meat', 'steak', 'beef'] },
    { emoji: '🥓', name: 'bacon', category: 'Food & Drink', keywords: ['bacon', 'meat'] },
    { emoji: '🍔', name: 'hamburger', category: 'Food & Drink', keywords: ['hamburger', 'burger', 'fast food'] },
    { emoji: '🍟', name: 'french fries', category: 'Food & Drink', keywords: ['french', 'fries', 'fast food'] },
    { emoji: '🍕', name: 'pizza', category: 'Food & Drink', keywords: ['pizza', 'slice', 'italian'] },
    { emoji: '🌭', name: 'hot dog', category: 'Food & Drink', keywords: ['hot', 'dog', 'fast food'] },
    { emoji: '🥪', name: 'sandwich', category: 'Food & Drink', keywords: ['sandwich', 'bread'] },
    { emoji: '🌮', name: 'taco', category: 'Food & Drink', keywords: ['taco', 'mexican'] },
    { emoji: '🌯', name: 'burrito', category: 'Food & Drink', keywords: ['burrito', 'wrap', 'mexican'] },
    { emoji: '🥙', name: 'stuffed flatbread', category: 'Food & Drink', keywords: ['flatbread', 'stuffed', 'pita'] },
    { emoji: '🧆', name: 'falafel', category: 'Food & Drink', keywords: ['falafel', 'middle eastern'] },
    { emoji: '🥚', name: 'egg', category: 'Food & Drink', keywords: ['egg', 'protein'] },
    { emoji: '🍳', name: 'cooking', category: 'Food & Drink', keywords: ['cooking', 'egg', 'fried'] },
    { emoji: '🥘', name: 'shallow pan of food', category: 'Food & Drink', keywords: ['pan', 'food', 'paella'] },
    { emoji: '🍲', name: 'pot of food', category: 'Food & Drink', keywords: ['pot', 'food', 'stew'] },
    { emoji: '🥣', name: 'bowl with spoon', category: 'Food & Drink', keywords: ['bowl', 'spoon', 'cereal'] },
    { emoji: '🥗', name: 'green salad', category: 'Food & Drink', keywords: ['salad', 'green', 'healthy'] },
    { emoji: '🍿', name: 'popcorn', category: 'Food & Drink', keywords: ['popcorn', 'snack', 'movie'] },
    { emoji: '🧈', name: 'butter', category: 'Food & Drink', keywords: ['butter', 'dairy'] },
    { emoji: '🧂', name: 'salt', category: 'Food & Drink', keywords: ['salt', 'seasoning'] },
    { emoji: '🥫', name: 'canned food', category: 'Food & Drink', keywords: ['canned', 'food', 'can'] },
    { emoji: '🍱', name: 'bento box', category: 'Food & Drink', keywords: ['bento', 'box', 'japanese'] },
    { emoji: '🍘', name: 'rice cracker', category: 'Food & Drink', keywords: ['rice', 'cracker', 'japanese'] },
    { emoji: '🍙', name: 'rice ball', category: 'Food & Drink', keywords: ['rice', 'ball', 'japanese'] },
    { emoji: '🍚', name: 'cooked rice', category: 'Food & Drink', keywords: ['rice', 'cooked'] },
    { emoji: '🍛', name: 'curry rice', category: 'Food & Drink', keywords: ['curry', 'rice', 'indian'] },
    { emoji: '🍜', name: 'steaming bowl', category: 'Food & Drink', keywords: ['steaming', 'bowl', 'noodles', 'ramen'] },
    { emoji: '🍝', name: 'spaghetti', category: 'Food & Drink', keywords: ['spaghetti', 'pasta', 'italian'] },
    { emoji: '🍠', name: 'roasted sweet potato', category: 'Food & Drink', keywords: ['sweet', 'potato', 'roasted'] },
    { emoji: '🍢', name: 'oden', category: 'Food & Drink', keywords: ['oden', 'japanese', 'skewer'] },
    { emoji: '🍣', name: 'sushi', category: 'Food & Drink', keywords: ['sushi', 'japanese', 'fish'] },
    { emoji: '🍤', name: 'fried shrimp', category: 'Food & Drink', keywords: ['fried', 'shrimp', 'japanese'] },
    { emoji: '🍥', name: 'fish cake with swirl', category: 'Food & Drink', keywords: ['fish', 'cake', 'japanese'] },
    { emoji: '🥮', name: 'moon cake', category: 'Food & Drink', keywords: ['moon', 'cake', 'chinese'] },
    { emoji: '🍡', name: 'dango', category: 'Food & Drink', keywords: ['dango', 'japanese', 'sweet'] },
    { emoji: '🥟', name: 'dumpling', category: 'Food & Drink', keywords: ['dumpling', 'chinese'] },
    { emoji: '🥠', name: 'fortune cookie', category: 'Food & Drink', keywords: ['fortune', 'cookie', 'chinese'] },
    { emoji: '🥡', name: 'takeout box', category: 'Food & Drink', keywords: ['takeout', 'box', 'chinese'] },
    { emoji: '🍦', name: 'soft ice cream', category: 'Food & Drink', keywords: ['ice', 'cream', 'soft', 'dessert'] },
    { emoji: '🍧', name: 'shaved ice', category: 'Food & Drink', keywords: ['shaved', 'ice', 'dessert'] },
    { emoji: '🍨', name: 'ice cream', category: 'Food & Drink', keywords: ['ice', 'cream', 'dessert'] },
    { emoji: '🍩', name: 'doughnut', category: 'Food & Drink', keywords: ['doughnut', 'donut', 'dessert'] },
    { emoji: '🍪', name: 'cookie', category: 'Food & Drink', keywords: ['cookie', 'dessert'] },
    { emoji: '🎂', name: 'birthday cake', category: 'Food & Drink', keywords: ['birthday', 'cake', 'dessert'] },
    { emoji: '🍰', name: 'shortcake', category: 'Food & Drink', keywords: ['shortcake', 'cake', 'dessert'] },
    { emoji: '🧁', name: 'cupcake', category: 'Food & Drink', keywords: ['cupcake', 'dessert'] },
    { emoji: '🥧', name: 'pie', category: 'Food & Drink', keywords: ['pie', 'dessert'] },
    { emoji: '🍫', name: 'chocolate bar', category: 'Food & Drink', keywords: ['chocolate', 'bar', 'dessert'] },
    { emoji: '🍬', name: 'candy', category: 'Food & Drink', keywords: ['candy', 'sweet', 'dessert'] },
    { emoji: '🍭', name: 'lollipop', category: 'Food & Drink', keywords: ['lollipop', 'candy', 'dessert'] },
    { emoji: '🍮', name: 'custard', category: 'Food & Drink', keywords: ['custard', 'dessert'] },
    { emoji: '🍯', name: 'honey pot', category: 'Food & Drink', keywords: ['honey', 'pot', 'sweet'] },
    { emoji: '☕', name: 'hot beverage', category: 'Food & Drink', keywords: ['coffee', 'hot', 'beverage'] },
    { emoji: '🫖', name: 'teapot', category: 'Food & Drink', keywords: ['teapot', 'tea'] },
    { emoji: '🍵', name: 'teacup without handle', category: 'Food & Drink', keywords: ['tea', 'cup', 'green'] },
    { emoji: '🍶', name: 'sake', category: 'Food & Drink', keywords: ['sake', 'japanese', 'alcohol'] },
    { emoji: '🍾', name: 'bottle with popping cork', category: 'Food & Drink', keywords: ['champagne', 'bottle', 'celebration'] },
    { emoji: '🍷', name: 'wine glass', category: 'Food & Drink', keywords: ['wine', 'glass', 'alcohol'] },
    { emoji: '🍸', name: 'cocktail glass', category: 'Food & Drink', keywords: ['cocktail', 'glass', 'alcohol'] },
    { emoji: '🍹', name: 'tropical drink', category: 'Food & Drink', keywords: ['tropical', 'drink', 'cocktail'] },
    { emoji: '🍺', name: 'beer mug', category: 'Food & Drink', keywords: ['beer', 'mug', 'alcohol'] },
    { emoji: '🍻', name: 'clinking beer mugs', category: 'Food & Drink', keywords: ['beer', 'mugs', 'cheers', 'alcohol'] },
    { emoji: '🥂', name: 'clinking glasses', category: 'Food & Drink', keywords: ['champagne', 'glasses', 'cheers'] },
    { emoji: '🥃', name: 'tumbler glass', category: 'Food & Drink', keywords: ['tumbler', 'glass', 'whiskey', 'alcohol'] },
    { emoji: '🧋', name: 'bubble tea', category: 'Food & Drink', keywords: ['bubble', 'tea', 'boba'] },
    { emoji: '🧃', name: 'beverage box', category: 'Food & Drink', keywords: ['juice', 'box', 'beverage'] },
    { emoji: '🧉', name: 'mate', category: 'Food & Drink', keywords: ['mate', 'drink', 'south american'] },
    { emoji: '🧊', name: 'ice cube', category: 'Food & Drink', keywords: ['ice', 'cube', 'cold'] },
    { emoji: '🥤', name: 'cup with straw', category: 'Food & Drink', keywords: ['cup', 'straw', 'drink'] },
    { emoji: '🧂', name: 'salt', category: 'Food & Drink', keywords: ['salt', 'seasoning'] },
    { emoji: '🥄', name: 'spoon', category: 'Food & Drink', keywords: ['spoon', 'utensil'] },
    { emoji: '🔪', name: 'kitchen knife', category: 'Food & Drink', keywords: ['knife', 'kitchen', 'utensil'] },
    { emoji: '🍴', name: 'fork and knife', category: 'Food & Drink', keywords: ['fork', 'knife', 'utensil'] },

    // Activities
    { emoji: '⚽', name: 'soccer ball', category: 'Activities', keywords: ['soccer', 'ball', 'football', 'sport'] },
    { emoji: '🏀', name: 'basketball', category: 'Activities', keywords: ['basketball', 'ball', 'sport'] },
    { emoji: '🏈', name: 'american football', category: 'Activities', keywords: ['american', 'football', 'ball', 'sport'] },
    { emoji: '⚾', name: 'baseball', category: 'Activities', keywords: ['baseball', 'ball', 'sport'] },
    { emoji: '🥎', name: 'softball', category: 'Activities', keywords: ['softball', 'ball', 'sport'] },
    { emoji: '🎾', name: 'tennis', category: 'Activities', keywords: ['tennis', 'ball', 'sport'] },
    { emoji: '🏐', name: 'volleyball', category: 'Activities', keywords: ['volleyball', 'ball', 'sport'] },
    { emoji: '🏉', name: 'rugby football', category: 'Activities', keywords: ['rugby', 'football', 'ball', 'sport'] },
    { emoji: '🥏', name: 'flying disc', category: 'Activities', keywords: ['frisbee', 'disc', 'sport'] },
    { emoji: '🎱', name: 'pool 8 ball', category: 'Activities', keywords: ['pool', '8', 'ball', 'billiards'] },
    { emoji: '🪀', name: 'yo-yo', category: 'Activities', keywords: ['yo-yo', 'toy'] },
    { emoji: '🏓', name: 'ping pong', category: 'Activities', keywords: ['ping', 'pong', 'table', 'tennis'] },
    { emoji: '🏸', name: 'badminton', category: 'Activities', keywords: ['badminton', 'racquet', 'sport'] },
    { emoji: '🏒', name: 'ice hockey', category: 'Activities', keywords: ['ice', 'hockey', 'stick', 'sport'] },
    { emoji: '🏑', name: 'field hockey', category: 'Activities', keywords: ['field', 'hockey', 'stick', 'sport'] },
    { emoji: '🥍', name: 'lacrosse', category: 'Activities', keywords: ['lacrosse', 'stick', 'sport'] },
    { emoji: '🏏', name: 'cricket game', category: 'Activities', keywords: ['cricket', 'bat', 'sport'] },
    { emoji: '🪃', name: 'boomerang', category: 'Activities', keywords: ['boomerang', 'australian'] },
    { emoji: '🥅', name: 'goal net', category: 'Activities', keywords: ['goal', 'net', 'sport'] },
    { emoji: '⛳', name: 'flag in hole', category: 'Activities', keywords: ['golf', 'flag', 'hole'] },
    { emoji: '🪁', name: 'kite', category: 'Activities', keywords: ['kite', 'flying'] },
    { emoji: '🛝', name: 'playground slide', category: 'Activities', keywords: ['slide', 'playground'] },
    { emoji: '🏹', name: 'bow and arrow', category: 'Activities', keywords: ['bow', 'arrow', 'archery'] },
    { emoji: '🎣', name: 'fishing pole', category: 'Activities', keywords: ['fishing', 'pole', 'fish'] },
    { emoji: '🤿', name: 'diving mask', category: 'Activities', keywords: ['diving', 'mask', 'snorkel'] },
    { emoji: '🥊', name: 'boxing glove', category: 'Activities', keywords: ['boxing', 'glove', 'sport'] },
    { emoji: '🥋', name: 'martial arts uniform', category: 'Activities', keywords: ['martial', 'arts', 'karate'] },
    { emoji: '🎽', name: 'running shirt', category: 'Activities', keywords: ['running', 'shirt', 'sport'] },
    { emoji: '🛹', name: 'skateboard', category: 'Activities', keywords: ['skateboard', 'skate'] },
    { emoji: '🛼', name: 'roller skate', category: 'Activities', keywords: ['roller', 'skate'] },
    { emoji: '🛷', name: 'sled', category: 'Activities', keywords: ['sled', 'sledding', 'snow'] },
    { emoji: '⛸️', name: 'ice skate', category: 'Activities', keywords: ['ice', 'skate', 'skating'] },
    { emoji: '🥌', name: 'curling stone', category: 'Activities', keywords: ['curling', 'stone', 'sport'] },
    { emoji: '🎿', name: 'skis', category: 'Activities', keywords: ['skis', 'skiing', 'snow'] },
    { emoji: '⛷️', name: 'skier', category: 'Activities', keywords: ['skier', 'skiing', 'snow'] },
    { emoji: '🏂', name: 'snowboarder', category: 'Activities', keywords: ['snowboarder', 'snowboarding', 'snow'] },
    { emoji: '🪂', name: 'parachute', category: 'Activities', keywords: ['parachute', 'skydiving'] },
    { emoji: '🏋️‍♀️', name: 'woman lifting weights', category: 'Activities', keywords: ['woman', 'lifting', 'weights', 'gym'] },
    { emoji: '🏋️‍♂️', name: 'man lifting weights', category: 'Activities', keywords: ['man', 'lifting', 'weights', 'gym'] },
    { emoji: '🤼‍♀️', name: 'women wrestling', category: 'Activities', keywords: ['women', 'wrestling', 'sport'] },
    { emoji: '🤼‍♂️', name: 'men wrestling', category: 'Activities', keywords: ['men', 'wrestling', 'sport'] },
    { emoji: '🤸‍♀️', name: 'woman cartwheeling', category: 'Activities', keywords: ['woman', 'cartwheel', 'gymnastics'] },
    { emoji: '🤸‍♂️', name: 'man cartwheeling', category: 'Activities', keywords: ['man', 'cartwheel', 'gymnastics'] },
    { emoji: '⛹️‍♀️', name: 'woman bouncing ball', category: 'Activities', keywords: ['woman', 'bouncing', 'ball', 'basketball'] },
    { emoji: '⛹️‍♂️', name: 'man bouncing ball', category: 'Activities', keywords: ['man', 'bouncing', 'ball', 'basketball'] },
    { emoji: '🤺', name: 'person fencing', category: 'Activities', keywords: ['fencing', 'sword', 'sport'] },
    { emoji: '🤾‍♀️', name: 'woman playing handball', category: 'Activities', keywords: ['woman', 'handball', 'sport'] },
    { emoji: '🤾‍♂️', name: 'man playing handball', category: 'Activities', keywords: ['man', 'handball', 'sport'] },
    { emoji: '🏌️‍♀️', name: 'woman golfing', category: 'Activities', keywords: ['woman', 'golf', 'sport'] },
    { emoji: '🏌️‍♂️', name: 'man golfing', category: 'Activities', keywords: ['man', 'golf', 'sport'] },
    { emoji: '🏇', name: 'horse racing', category: 'Activities', keywords: ['horse', 'racing', 'jockey'] },
    { emoji: '🧘‍♀️', name: 'woman in lotus position', category: 'Activities', keywords: ['woman', 'meditation', 'yoga'] },
    { emoji: '🧘‍♂️', name: 'man in lotus position', category: 'Activities', keywords: ['man', 'meditation', 'yoga'] },
    { emoji: '🏄‍♀️', name: 'woman surfing', category: 'Activities', keywords: ['woman', 'surfing', 'wave'] },
    { emoji: '🏄‍♂️', name: 'man surfing', category: 'Activities', keywords: ['man', 'surfing', 'wave'] },
    { emoji: '🏊‍♀️', name: 'woman swimming', category: 'Activities', keywords: ['woman', 'swimming', 'pool'] },
    { emoji: '🏊‍♂️', name: 'man swimming', category: 'Activities', keywords: ['man', 'swimming', 'pool'] },
    { emoji: '🤽‍♀️', name: 'woman playing water polo', category: 'Activities', keywords: ['woman', 'water', 'polo', 'sport'] },
    { emoji: '🤽‍♂️', name: 'man playing water polo', category: 'Activities', keywords: ['man', 'water', 'polo', 'sport'] },
    { emoji: '🚣‍♀️', name: 'woman rowing boat', category: 'Activities', keywords: ['woman', 'rowing', 'boat'] },
    { emoji: '🚣‍♂️', name: 'man rowing boat', category: 'Activities', keywords: ['man', 'rowing', 'boat'] },
    { emoji: '🧗‍♀️', name: 'woman climbing', category: 'Activities', keywords: ['woman', 'climbing', 'rock'] },
    { emoji: '🧗‍♂️', name: 'man climbing', category: 'Activities', keywords: ['man', 'climbing', 'rock'] },
    { emoji: '🚵‍♀️', name: 'woman mountain biking', category: 'Activities', keywords: ['woman', 'mountain', 'biking'] },
    { emoji: '🚵‍♂️', name: 'man mountain biking', category: 'Activities', keywords: ['man', 'mountain', 'biking'] },
    { emoji: '🚴‍♀️', name: 'woman biking', category: 'Activities', keywords: ['woman', 'biking', 'bicycle'] },
    { emoji: '🚴‍♂️', name: 'man biking', category: 'Activities', keywords: ['man', 'biking', 'bicycle'] },
    { emoji: '🏆', name: 'trophy', category: 'Activities', keywords: ['trophy', 'award', 'winner'] },
    { emoji: '🥇', name: 'first place medal', category: 'Activities', keywords: ['first', 'place', 'medal', 'gold'] },
    { emoji: '🥈', name: 'second place medal', category: 'Activities', keywords: ['second', 'place', 'medal', 'silver'] },
    { emoji: '🥉', name: 'third place medal', category: 'Activities', keywords: ['third', 'place', 'medal', 'bronze'] },
    { emoji: '🏅', name: 'sports medal', category: 'Activities', keywords: ['sports', 'medal', 'award'] },
    { emoji: '🎖️', name: 'military medal', category: 'Activities', keywords: ['military', 'medal', 'honor'] },
    { emoji: '🏵️', name: 'rosette', category: 'Activities', keywords: ['rosette', 'flower', 'award'] },
    { emoji: '🎗️', name: 'reminder ribbon', category: 'Activities', keywords: ['reminder', 'ribbon', 'awareness'] },
    { emoji: '🎫', name: 'ticket', category: 'Activities', keywords: ['ticket', 'admission'] },
    { emoji: '🎟️', name: 'admission tickets', category: 'Activities', keywords: ['admission', 'tickets'] },
    { emoji: '🎪', name: 'circus tent', category: 'Activities', keywords: ['circus', 'tent'] },
    { emoji: '🤹‍♀️', name: 'woman juggling', category: 'Activities', keywords: ['woman', 'juggling'] },
    { emoji: '🤹‍♂️', name: 'man juggling', category: 'Activities', keywords: ['man', 'juggling'] },
    { emoji: '🎭', name: 'performing arts', category: 'Activities', keywords: ['performing', 'arts', 'theater', 'drama'] },
    { emoji: '🩰', name: 'ballet shoes', category: 'Activities', keywords: ['ballet', 'shoes', 'dance'] },
    { emoji: '🎨', name: 'artist palette', category: 'Activities', keywords: ['artist', 'palette', 'art', 'paint'] },
    { emoji: '🎬', name: 'clapper board', category: 'Activities', keywords: ['clapper', 'board', 'movie', 'film'] },
    { emoji: '🎤', name: 'microphone', category: 'Activities', keywords: ['microphone', 'sing', 'karaoke'] },
    { emoji: '🎧', name: 'headphone', category: 'Activities', keywords: ['headphone', 'music'] },
    { emoji: '🎼', name: 'musical score', category: 'Activities', keywords: ['musical', 'score', 'notes'] },
    { emoji: '🎵', name: 'musical note', category: 'Activities', keywords: ['musical', 'note', 'music'] },
    { emoji: '🎶', name: 'musical notes', category: 'Activities', keywords: ['musical', 'notes', 'music'] },
    { emoji: '🪘', name: 'long drum', category: 'Activities', keywords: ['long', 'drum', 'music'] },
    { emoji: '🥁', name: 'drum', category: 'Activities', keywords: ['drum', 'music'] },
    { emoji: '🪗', name: 'accordion', category: 'Activities', keywords: ['accordion', 'music'] },
    { emoji: '🎺', name: 'trumpet', category: 'Activities', keywords: ['trumpet', 'music'] },
    { emoji: '🎷', name: 'saxophone', category: 'Activities', keywords: ['saxophone', 'music'] },
    { emoji: '🎸', name: 'guitar', category: 'Activities', keywords: ['guitar', 'music'] },
    { emoji: '🪕', name: 'banjo', category: 'Activities', keywords: ['banjo', 'music'] },
    { emoji: '🎻', name: 'violin', category: 'Activities', keywords: ['violin', 'music'] },
    { emoji: '🎹', name: 'musical keyboard', category: 'Activities', keywords: ['keyboard', 'piano', 'music'] },
    { emoji: '🪇', name: 'maracas', category: 'Activities', keywords: ['maracas', 'music'] },
    { emoji: '🪈', name: 'flute', category: 'Activities', keywords: ['flute', 'music'] },
    { emoji: '🎲', name: 'game die', category: 'Activities', keywords: ['die', 'dice', 'game'] },
    { emoji: '♠️', name: 'spade suit', category: 'Activities', keywords: ['spade', 'suit', 'cards'] },
    { emoji: '♥️', name: 'heart suit', category: 'Activities', keywords: ['heart', 'suit', 'cards'] },
    { emoji: '♦️', name: 'diamond suit', category: 'Activities', keywords: ['diamond', 'suit', 'cards'] },
    { emoji: '♣️', name: 'club suit', category: 'Activities', keywords: ['club', 'suit', 'cards'] },
    { emoji: '♟️', name: 'chess pawn', category: 'Activities', keywords: ['chess', 'pawn'] },
    { emoji: '🃏', name: 'joker', category: 'Activities', keywords: ['joker', 'cards'] },
    { emoji: '🀄', name: 'mahjong red dragon', category: 'Activities', keywords: ['mahjong', 'red', 'dragon'] },
    { emoji: '🎴', name: 'flower playing cards', category: 'Activities', keywords: ['flower', 'cards', 'japanese'] },
    { emoji: '🎮', name: 'video game', category: 'Activities', keywords: ['video', 'game', 'controller'] },
    { emoji: '🕹️', name: 'joystick', category: 'Activities', keywords: ['joystick', 'game'] },
    { emoji: '🎰', name: 'slot machine', category: 'Activities', keywords: ['slot', 'machine', 'gambling'] },
    { emoji: '🎳', name: 'bowling', category: 'Activities', keywords: ['bowling', 'pins', 'ball'] },

    // Travel & Places
    { emoji: '🚗', name: 'automobile', category: 'Travel & Places', keywords: ['car', 'automobile', 'vehicle'] },
    { emoji: '🚕', name: 'taxi', category: 'Travel & Places', keywords: ['taxi', 'cab', 'vehicle'] },
    { emoji: '🚙', name: 'sport utility vehicle', category: 'Travel & Places', keywords: ['suv', 'vehicle', 'car'] },
    { emoji: '🚌', name: 'bus', category: 'Travel & Places', keywords: ['bus', 'vehicle', 'transport'] },
    { emoji: '🚎', name: 'trolleybus', category: 'Travel & Places', keywords: ['trolleybus', 'vehicle'] },
    { emoji: '🏎️', name: 'racing car', category: 'Travel & Places', keywords: ['racing', 'car', 'fast'] },
    { emoji: '🚓', name: 'police car', category: 'Travel & Places', keywords: ['police', 'car', 'vehicle'] },
    { emoji: '🚑', name: 'ambulance', category: 'Travel & Places', keywords: ['ambulance', 'emergency', 'vehicle'] },
    { emoji: '🚒', name: 'fire engine', category: 'Travel & Places', keywords: ['fire', 'engine', 'truck'] },
    { emoji: '🚐', name: 'minibus', category: 'Travel & Places', keywords: ['minibus', 'van', 'vehicle'] },
    { emoji: '🛻', name: 'pickup truck', category: 'Travel & Places', keywords: ['pickup', 'truck', 'vehicle'] },
    { emoji: '🚚', name: 'delivery truck', category: 'Travel & Places', keywords: ['delivery', 'truck', 'vehicle'] },
    { emoji: '🚛', name: 'articulated lorry', category: 'Travel & Places', keywords: ['lorry', 'truck', 'big'] },
    { emoji: '🚜', name: 'tractor', category: 'Travel & Places', keywords: ['tractor', 'farm', 'vehicle'] },
    { emoji: '🏍️', name: 'motorcycle', category: 'Travel & Places', keywords: ['motorcycle', 'bike', 'vehicle'] },
    { emoji: '🛵', name: 'motor scooter', category: 'Travel & Places', keywords: ['scooter', 'motor', 'vehicle'] },
    { emoji: '🚲', name: 'bicycle', category: 'Travel & Places', keywords: ['bicycle', 'bike', 'vehicle'] },
    { emoji: '🛴', name: 'kick scooter', category: 'Travel & Places', keywords: ['scooter', 'kick', 'vehicle'] },
    { emoji: '🛹', name: 'skateboard', category: 'Travel & Places', keywords: ['skateboard', 'skate'] },
    { emoji: '🛼', name: 'roller skate', category: 'Travel & Places', keywords: ['roller', 'skate'] },
    { emoji: '🚁', name: 'helicopter', category: 'Travel & Places', keywords: ['helicopter', 'aircraft'] },
    { emoji: '🛩️', name: 'small airplane', category: 'Travel & Places', keywords: ['airplane', 'small', 'aircraft'] },
    { emoji: '✈️', name: 'airplane', category: 'Travel & Places', keywords: ['airplane', 'aircraft', 'flight'] },
    { emoji: '🛫', name: 'airplane departure', category: 'Travel & Places', keywords: ['airplane', 'departure', 'takeoff'] },
    { emoji: '🛬', name: 'airplane arrival', category: 'Travel & Places', keywords: ['airplane', 'arrival', 'landing'] },
    { emoji: '🪂', name: 'parachute', category: 'Travel & Places', keywords: ['parachute', 'skydiving'] },
    { emoji: '💺', name: 'seat', category: 'Travel & Places', keywords: ['seat', 'chair', 'airplane'] },
    { emoji: '🚀', name: 'rocket', category: 'Travel & Places', keywords: ['rocket', 'space', 'launch'] },
    { emoji: '🛸', name: 'flying saucer', category: 'Travel & Places', keywords: ['ufo', 'flying', 'saucer', 'alien'] },
    { emoji: '🚉', name: 'station', category: 'Travel & Places', keywords: ['station', 'train', 'railway'] },
    { emoji: '🚞', name: 'mountain railway', category: 'Travel & Places', keywords: ['mountain', 'railway', 'train'] },
    { emoji: '🚝', name: 'monorail', category: 'Travel & Places', keywords: ['monorail', 'train'] },
    { emoji: '🚄', name: 'high-speed train', category: 'Travel & Places', keywords: ['high-speed', 'train', 'bullet'] },
    { emoji: '🚅', name: 'bullet train', category: 'Travel & Places', keywords: ['bullet', 'train', 'fast'] },
    { emoji: '🚈', name: 'light rail', category: 'Travel & Places', keywords: ['light', 'rail', 'train'] },
    { emoji: '🚂', name: 'locomotive', category: 'Travel & Places', keywords: ['locomotive', 'train', 'steam'] },
    { emoji: '🚃', name: 'railway car', category: 'Travel & Places', keywords: ['railway', 'car', 'train'] },
    { emoji: '🚋', name: 'tram car', category: 'Travel & Places', keywords: ['tram', 'car', 'streetcar'] },
    { emoji: '🚆', name: 'train', category: 'Travel & Places', keywords: ['train', 'railway'] },
    { emoji: '🚇', name: 'metro', category: 'Travel & Places', keywords: ['metro', 'subway', 'underground'] },
    { emoji: '🚊', name: 'tram', category: 'Travel & Places', keywords: ['tram', 'streetcar'] },
    { emoji: '🚟', name: 'suspension railway', category: 'Travel & Places', keywords: ['suspension', 'railway'] },
    { emoji: '🚠', name: 'mountain cableway', category: 'Travel & Places', keywords: ['mountain', 'cableway', 'cable'] },
    { emoji: '🚡', name: 'aerial tramway', category: 'Travel & Places', keywords: ['aerial', 'tramway', 'cable'] },
    { emoji: '⛴️', name: 'ferry', category: 'Travel & Places', keywords: ['ferry', 'boat', 'ship'] },
    { emoji: '🛥️', name: 'motor boat', category: 'Travel & Places', keywords: ['motor', 'boat', 'speedboat'] },
    { emoji: '🚤', name: 'speedboat', category: 'Travel & Places', keywords: ['speedboat', 'boat', 'fast'] },
    { emoji: '🛳️', name: 'passenger ship', category: 'Travel & Places', keywords: ['passenger', 'ship', 'cruise'] },
    { emoji: '⛵', name: 'sailboat', category: 'Travel & Places', keywords: ['sailboat', 'sail', 'boat'] },
    { emoji: '🚣', name: 'rowboat', category: 'Travel & Places', keywords: ['rowboat', 'boat', 'rowing'] },
    { emoji: '🛶', name: 'canoe', category: 'Travel & Places', keywords: ['canoe', 'boat', 'paddle'] },
    { emoji: '🚢', name: 'ship', category: 'Travel & Places', keywords: ['ship', 'boat', 'large'] },
    { emoji: '🛟', name: 'ring buoy', category: 'Travel & Places', keywords: ['ring', 'buoy', 'life', 'preserver'] },
    { emoji: '⚓', name: 'anchor', category: 'Travel & Places', keywords: ['anchor', 'ship', 'boat'] },
    { emoji: '🪝', name: 'hook', category: 'Travel & Places', keywords: ['hook', 'fishing'] },
    { emoji: '⛽', name: 'fuel pump', category: 'Travel & Places', keywords: ['fuel', 'pump', 'gas'] },
    { emoji: '🚨', name: 'police car light', category: 'Travel & Places', keywords: ['police', 'car', 'light', 'siren'] },
    { emoji: '🚥', name: 'horizontal traffic light', category: 'Travel & Places', keywords: ['traffic', 'light', 'horizontal'] },
    { emoji: '🚦', name: 'vertical traffic light', category: 'Travel & Places', keywords: ['traffic', 'light', 'vertical'] },
    { emoji: '🛑', name: 'stop sign', category: 'Travel & Places', keywords: ['stop', 'sign'] },
    { emoji: '🚧', name: 'construction', category: 'Travel & Places', keywords: ['construction', 'barrier'] },
    { emoji: '🏁', name: 'chequered flag', category: 'Travel & Places', keywords: ['chequered', 'flag', 'racing'] },
    { emoji: '🏳️', name: 'white flag', category: 'Travel & Places', keywords: ['white', 'flag', 'surrender'] },
    { emoji: '🏴', name: 'black flag', category: 'Travel & Places', keywords: ['black', 'flag'] },
    { emoji: '🏴‍☠️', name: 'pirate flag', category: 'Travel & Places', keywords: ['pirate', 'flag', 'skull'] },
    { emoji: '🏳️‍🌈', name: 'rainbow flag', category: 'Travel & Places', keywords: ['rainbow', 'flag', 'pride'] },
    { emoji: '🏳️‍⚧️', name: 'transgender flag', category: 'Travel & Places', keywords: ['transgender', 'flag'] },
    { emoji: '🇺🇸', name: 'flag: United States', category: 'Travel & Places', keywords: ['flag', 'united', 'states', 'america'] },

    // Objects
    { emoji: '⌚', name: 'watch', category: 'Objects', keywords: ['watch', 'time'] },
    { emoji: '📱', name: 'mobile phone', category: 'Objects', keywords: ['mobile', 'phone', 'smartphone'] },
    { emoji: '📲', name: 'mobile phone with arrow', category: 'Objects', keywords: ['mobile', 'phone', 'call'] },
    { emoji: '💻', name: 'laptop computer', category: 'Objects', keywords: ['laptop', 'computer'] },
    { emoji: '⌨️', name: 'keyboard', category: 'Objects', keywords: ['keyboard', 'computer'] },
    { emoji: '🖥️', name: 'desktop computer', category: 'Objects', keywords: ['desktop', 'computer'] },
    { emoji: '🖨️', name: 'printer', category: 'Objects', keywords: ['printer'] },
    { emoji: '🖱️', name: 'computer mouse', category: 'Objects', keywords: ['mouse', 'computer'] },
    { emoji: '🖲️', name: 'trackball', category: 'Objects', keywords: ['trackball', 'computer'] },
    { emoji: '🕹️', name: 'joystick', category: 'Objects', keywords: ['joystick', 'game'] },
    { emoji: '🗜️', name: 'clamp', category: 'Objects', keywords: ['clamp', 'tool'] },
    { emoji: '💽', name: 'computer disk', category: 'Objects', keywords: ['disk', 'computer', 'minidisc'] },
    { emoji: '💾', name: 'floppy disk', category: 'Objects', keywords: ['floppy', 'disk', 'save'] },
    { emoji: '💿', name: 'optical disk', category: 'Objects', keywords: ['cd', 'disk', 'optical'] },
    { emoji: '📀', name: 'dvd', category: 'Objects', keywords: ['dvd', 'disk'] },
    { emoji: '🧮', name: 'abacus', category: 'Objects', keywords: ['abacus', 'calculation'] },
    { emoji: '📹', name: 'video camera', category: 'Objects', keywords: ['video', 'camera'] },
    { emoji: '🎥', name: 'movie camera', category: 'Objects', keywords: ['movie', 'camera', 'film'] },
    { emoji: '📽️', name: 'film projector', category: 'Objects', keywords: ['film', 'projector', 'movie'] },
    { emoji: '🎞️', name: 'film frames', category: 'Objects', keywords: ['film', 'frames', 'movie'] },
    { emoji: '📞', name: 'telephone receiver', category: 'Objects', keywords: ['telephone', 'receiver', 'phone'] },
    { emoji: '☎️', name: 'telephone', category: 'Objects', keywords: ['telephone', 'phone'] },
    { emoji: '📟', name: 'pager', category: 'Objects', keywords: ['pager', 'beeper'] },
    { emoji: '📠', name: 'fax machine', category: 'Objects', keywords: ['fax', 'machine'] },
    { emoji: '📺', name: 'television', category: 'Objects', keywords: ['television', 'tv'] },
    { emoji: '📻', name: 'radio', category: 'Objects', keywords: ['radio'] },
    { emoji: '🎙️', name: 'studio microphone', category: 'Objects', keywords: ['studio', 'microphone'] },
    { emoji: '🎚️', name: 'level slider', category: 'Objects', keywords: ['level', 'slider'] },
    { emoji: '🎛️', name: 'control knobs', category: 'Objects', keywords: ['control', 'knobs'] },
    { emoji: '🧭', name: 'compass', category: 'Objects', keywords: ['compass', 'direction'] },
    { emoji: '⏱️', name: 'stopwatch', category: 'Objects', keywords: ['stopwatch', 'timer'] },
    { emoji: '⏲️', name: 'timer clock', category: 'Objects', keywords: ['timer', 'clock'] },
    { emoji: '⏰', name: 'alarm clock', category: 'Objects', keywords: ['alarm', 'clock'] },
    { emoji: '🕰️', name: 'mantelpiece clock', category: 'Objects', keywords: ['mantelpiece', 'clock'] },
    { emoji: '⌛', name: 'hourglass done', category: 'Objects', keywords: ['hourglass', 'done', 'time'] },
    { emoji: '⏳', name: 'hourglass not done', category: 'Objects', keywords: ['hourglass', 'not', 'done', 'time'] },
    { emoji: '📡', name: 'satellite antenna', category: 'Objects', keywords: ['satellite', 'antenna'] },
    { emoji: '🔋', name: 'battery', category: 'Objects', keywords: ['battery', 'power'] },
    { emoji: '🪫', name: 'low battery', category: 'Objects', keywords: ['low', 'battery', 'power'] },
    { emoji: '🔌', name: 'electric plug', category: 'Objects', keywords: ['electric', 'plug', 'power'] },
    { emoji: '💡', name: 'light bulb', category: 'Objects', keywords: ['light', 'bulb', 'idea'] },
    { emoji: '🔦', name: 'flashlight', category: 'Objects', keywords: ['flashlight', 'torch'] },
    { emoji: '🕯️', name: 'candle', category: 'Objects', keywords: ['candle', 'light'] },
    { emoji: '🪔', name: 'diya lamp', category: 'Objects', keywords: ['diya', 'lamp', 'oil'] },
    { emoji: '🧯', name: 'fire extinguisher', category: 'Objects', keywords: ['fire', 'extinguisher'] },
    { emoji: '🛢️', name: 'oil drum', category: 'Objects', keywords: ['oil', 'drum'] },
    { emoji: '🛒', name: 'shopping cart', category: 'Objects', keywords: ['shopping', 'cart', 'trolley'] },
    { emoji: '💸', name: 'money with wings', category: 'Objects', keywords: ['money', 'wings', 'fly'] },
    { emoji: '💵', name: 'dollar banknote', category: 'Objects', keywords: ['dollar', 'banknote', 'money'] },
    { emoji: '💴', name: 'yen banknote', category: 'Objects', keywords: ['yen', 'banknote', 'money'] },
    { emoji: '💶', name: 'euro banknote', category: 'Objects', keywords: ['euro', 'banknote', 'money'] },
    { emoji: '💷', name: 'pound banknote', category: 'Objects', keywords: ['pound', 'banknote', 'money'] },
    { emoji: '🪙', name: 'coin', category: 'Objects', keywords: ['coin', 'money'] },
    { emoji: '💰', name: 'money bag', category: 'Objects', keywords: ['money', 'bag', 'dollar'] },
    { emoji: '💳', name: 'credit card', category: 'Objects', keywords: ['credit', 'card', 'payment'] },
    { emoji: '🧾', name: 'receipt', category: 'Objects', keywords: ['receipt', 'bill'] },
    { emoji: '💎', name: 'gem stone', category: 'Objects', keywords: ['gem', 'stone', 'diamond'] },
    { emoji: '⚖️', name: 'balance scale', category: 'Objects', keywords: ['balance', 'scale', 'justice'] },
    { emoji: '🧰', name: 'toolbox', category: 'Objects', keywords: ['toolbox', 'tools'] },
    { emoji: '🔧', name: 'wrench', category: 'Objects', keywords: ['wrench', 'tool'] },
    { emoji: '🔨', name: 'hammer', category: 'Objects', keywords: ['hammer', 'tool'] },
    { emoji: '⚒️', name: 'hammer and pick', category: 'Objects', keywords: ['hammer', 'pick', 'tools'] },
    { emoji: '🛠️', name: 'hammer and wrench', category: 'Objects', keywords: ['hammer', 'wrench', 'tools'] },
    { emoji: '⛏️', name: 'pick', category: 'Objects', keywords: ['pick', 'tool', 'mining'] },
    { emoji: '🪚', name: 'carpentry saw', category: 'Objects', keywords: ['saw', 'carpentry', 'tool'] },
    { emoji: '🔩', name: 'nut and bolt', category: 'Objects', keywords: ['nut', 'bolt', 'hardware'] },
    { emoji: '⚙️', name: 'gear', category: 'Objects', keywords: ['gear', 'cog', 'settings'] },
    { emoji: '🪜', name: 'ladder', category: 'Objects', keywords: ['ladder', 'climb'] },
    { emoji: '⛓️', name: 'chains', category: 'Objects', keywords: ['chains', 'link'] },
    { emoji: '🪝', name: 'hook', category: 'Objects', keywords: ['hook'] },
    { emoji: '🧲', name: 'magnet', category: 'Objects', keywords: ['magnet', 'attraction'] },
    { emoji: '🔫', name: 'pistol', category: 'Objects', keywords: ['pistol', 'gun', 'weapon'] },
    { emoji: '💣', name: 'bomb', category: 'Objects', keywords: ['bomb', 'explosive'] },
    { emoji: '🧨', name: 'firecracker', category: 'Objects', keywords: ['firecracker', 'explosive'] },
    { emoji: '🪓', name: 'axe', category: 'Objects', keywords: ['axe', 'tool', 'chop'] },
    { emoji: '🔪', name: 'kitchen knife', category: 'Objects', keywords: ['knife', 'kitchen', 'cut'] },
    { emoji: '🗡️', name: 'dagger', category: 'Objects', keywords: ['dagger', 'knife', 'weapon'] },
    { emoji: '⚔️', name: 'crossed swords', category: 'Objects', keywords: ['crossed', 'swords', 'weapon'] },
    { emoji: '🛡️', name: 'shield', category: 'Objects', keywords: ['shield', 'protection'] },
    { emoji: '🚬', name: 'cigarette', category: 'Objects', keywords: ['cigarette', 'smoking'] },
    { emoji: '⚰️', name: 'coffin', category: 'Objects', keywords: ['coffin', 'death'] },
    { emoji: '🪦', name: 'headstone', category: 'Objects', keywords: ['headstone', 'grave', 'death'] },
    { emoji: '⚱️', name: 'funeral urn', category: 'Objects', keywords: ['funeral', 'urn', 'death'] },
    { emoji: '🏺', name: 'amphora', category: 'Objects', keywords: ['amphora', 'jar', 'vase'] },
    { emoji: '🔮', name: 'crystal ball', category: 'Objects', keywords: ['crystal', 'ball', 'fortune'] },
    { emoji: '📿', name: 'prayer beads', category: 'Objects', keywords: ['prayer', 'beads', 'rosary'] },
    { emoji: '🧿', name: 'nazar amulet', category: 'Objects', keywords: ['nazar', 'amulet', 'evil', 'eye'] },
    { emoji: '💈', name: 'barber pole', category: 'Objects', keywords: ['barber', 'pole', 'haircut'] },
    { emoji: '⚗️', name: 'alembic', category: 'Objects', keywords: ['alembic', 'chemistry'] },
    { emoji: '🔭', name: 'telescope', category: 'Objects', keywords: ['telescope', 'astronomy'] },
    { emoji: '🔬', name: 'microscope', category: 'Objects', keywords: ['microscope', 'science'] },
    { emoji: '🕳️', name: 'hole', category: 'Objects', keywords: ['hole', 'empty'] },
    { emoji: '🩹', name: 'adhesive bandage', category: 'Objects', keywords: ['bandage', 'adhesive', 'medical'] },
    { emoji: '🩺', name: 'stethoscope', category: 'Objects', keywords: ['stethoscope', 'medical'] },
    { emoji: '💊', name: 'pill', category: 'Objects', keywords: ['pill', 'medicine'] },
    { emoji: '💉', name: 'syringe', category: 'Objects', keywords: ['syringe', 'injection', 'medical'] },
    { emoji: '🩸', name: 'drop of blood', category: 'Objects', keywords: ['blood', 'drop', 'medical'] },
    { emoji: '🧬', name: 'dna', category: 'Objects', keywords: ['dna', 'genetics'] },
    { emoji: '🦠', name: 'microbe', category: 'Objects', keywords: ['microbe', 'virus', 'bacteria'] },
    { emoji: '🧫', name: 'petri dish', category: 'Objects', keywords: ['petri', 'dish', 'laboratory'] },
    { emoji: '🧪', name: 'test tube', category: 'Objects', keywords: ['test', 'tube', 'science'] },
    { emoji: '🌡️', name: 'thermometer', category: 'Objects', keywords: ['thermometer', 'temperature'] },
    { emoji: '🧹', name: 'broom', category: 'Objects', keywords: ['broom', 'cleaning'] },
    { emoji: '🧺', name: 'basket', category: 'Objects', keywords: ['basket', 'container'] },
    { emoji: '🧻', name: 'roll of paper', category: 'Objects', keywords: ['roll', 'paper', 'toilet'] },
    { emoji: '🚽', name: 'toilet', category: 'Objects', keywords: ['toilet', 'bathroom'] },
    { emoji: '🚰', name: 'potable water', category: 'Objects', keywords: ['potable', 'water', 'drinking'] },
    { emoji: '🚿', name: 'shower', category: 'Objects', keywords: ['shower', 'bathroom'] },
    { emoji: '🛁', name: 'bathtub', category: 'Objects', keywords: ['bathtub', 'bath', 'bathroom'] },
    { emoji: '🛀', name: 'person taking bath', category: 'Objects', keywords: ['person', 'bath', 'bathing'] },
    { emoji: '🧴', name: 'lotion bottle', category: 'Objects', keywords: ['lotion', 'bottle', 'cosmetics'] },
    { emoji: '🧷', name: 'safety pin', category: 'Objects', keywords: ['safety', 'pin'] },
    { emoji: '🧸', name: 'teddy bear', category: 'Objects', keywords: ['teddy', 'bear', 'toy'] },
    { emoji: '🧵', name: 'thread', category: 'Objects', keywords: ['thread', 'sewing'] },
    { emoji: '🧶', name: 'yarn', category: 'Objects', keywords: ['yarn', 'knitting'] },
    { emoji: '🪡', name: 'sewing needle', category: 'Objects', keywords: ['sewing', 'needle'] },
    { emoji: '🪢', name: 'knot', category: 'Objects', keywords: ['knot', 'rope'] },
    { emoji: '🪣', name: 'bucket', category: 'Objects', keywords: ['bucket', 'container'] },
    { emoji: '🪤', name: 'mouse trap', category: 'Objects', keywords: ['mouse', 'trap'] },
    { emoji: '🪥', name: 'toothbrush', category: 'Objects', keywords: ['toothbrush', 'dental'] },
    { emoji: '🪦', name: 'headstone', category: 'Objects', keywords: ['headstone', 'grave'] },
    { emoji: '🪧', name: 'placard', category: 'Objects', keywords: ['placard', 'sign'] },

    // Symbols
    { emoji: '❤️', name: 'red heart', category: 'Symbols', keywords: ['red', 'heart', 'love'] },
    { emoji: '🧡', name: 'orange heart', category: 'Symbols', keywords: ['orange', 'heart', 'love'] },
    { emoji: '💛', name: 'yellow heart', category: 'Symbols', keywords: ['yellow', 'heart', 'love'] },
    { emoji: '💚', name: 'green heart', category: 'Symbols', keywords: ['green', 'heart', 'love'] },
    { emoji: '💙', name: 'blue heart', category: 'Symbols', keywords: ['blue', 'heart', 'love'] },
    { emoji: '💜', name: 'purple heart', category: 'Symbols', keywords: ['purple', 'heart', 'love'] },
    { emoji: '🖤', name: 'black heart', category: 'Symbols', keywords: ['black', 'heart', 'love'] },
    { emoji: '🤍', name: 'white heart', category: 'Symbols', keywords: ['white', 'heart', 'love'] },
    { emoji: '🤎', name: 'brown heart', category: 'Symbols', keywords: ['brown', 'heart', 'love'] },
    { emoji: '💔', name: 'broken heart', category: 'Symbols', keywords: ['broken', 'heart', 'sad'] },
    { emoji: '❣️', name: 'heart exclamation', category: 'Symbols', keywords: ['heart', 'exclamation', 'love'] },
    { emoji: '💕', name: 'two hearts', category: 'Symbols', keywords: ['two', 'hearts', 'love'] },
    { emoji: '💞', name: 'revolving hearts', category: 'Symbols', keywords: ['revolving', 'hearts', 'love'] },
    { emoji: '💓', name: 'beating heart', category: 'Symbols', keywords: ['beating', 'heart', 'love'] },
    { emoji: '💗', name: 'growing heart', category: 'Symbols', keywords: ['growing', 'heart', 'love'] },
    { emoji: '💖', name: 'sparkling heart', category: 'Symbols', keywords: ['sparkling', 'heart', 'love'] },
    { emoji: '💘', name: 'heart with arrow', category: 'Symbols', keywords: ['heart', 'arrow', 'cupid', 'love'] },
    { emoji: '💝', name: 'heart with ribbon', category: 'Symbols', keywords: ['heart', 'ribbon', 'gift', 'love'] },
    { emoji: '💟', name: 'heart decoration', category: 'Symbols', keywords: ['heart', 'decoration', 'love'] },
    { emoji: '☮️', name: 'peace symbol', category: 'Symbols', keywords: ['peace', 'symbol'] },
    { emoji: '✝️', name: 'latin cross', category: 'Symbols', keywords: ['latin', 'cross', 'christian'] },
    { emoji: '☪️', name: 'star and crescent', category: 'Symbols', keywords: ['star', 'crescent', 'islam'] },
    { emoji: '🕉️', name: 'om', category: 'Symbols', keywords: ['om', 'hinduism', 'buddhism'] },
    { emoji: '☸️', name: 'wheel of dharma', category: 'Symbols', keywords: ['wheel', 'dharma', 'buddhism'] },
    { emoji: '✡️', name: 'star of david', category: 'Symbols', keywords: ['star', 'david', 'judaism'] },
    { emoji: '🔯', name: 'dotted six-pointed star', category: 'Symbols', keywords: ['dotted', 'six-pointed', 'star'] },
    { emoji: '🕎', name: 'menorah', category: 'Symbols', keywords: ['menorah', 'judaism'] },
    { emoji: '☯️', name: 'yin yang', category: 'Symbols', keywords: ['yin', 'yang', 'balance'] },
    { emoji: '☦️', name: 'orthodox cross', category: 'Symbols', keywords: ['orthodox', 'cross', 'christian'] },
    { emoji: '🛐', name: 'place of worship', category: 'Symbols', keywords: ['place', 'worship', 'religion'] },
    { emoji: '⛎', name: 'ophiuchus', category: 'Symbols', keywords: ['ophiuchus', 'zodiac'] },
    { emoji: '♈', name: 'aries', category: 'Symbols', keywords: ['aries', 'zodiac'] },
    { emoji: '♉', name: 'taurus', category: 'Symbols', keywords: ['taurus', 'zodiac'] },
    { emoji: '♊', name: 'gemini', category: 'Symbols', keywords: ['gemini', 'zodiac'] },
    { emoji: '♋', name: 'cancer', category: 'Symbols', keywords: ['cancer', 'zodiac'] },
    { emoji: '♌', name: 'leo', category: 'Symbols', keywords: ['leo', 'zodiac'] },
    { emoji: '♍', name: 'virgo', category: 'Symbols', keywords: ['virgo', 'zodiac'] },
    { emoji: '♎', name: 'libra', category: 'Symbols', keywords: ['libra', 'zodiac'] },
    { emoji: '♏', name: 'scorpio', category: 'Symbols', keywords: ['scorpio', 'zodiac'] },
    { emoji: '♐', name: 'sagittarius', category: 'Symbols', keywords: ['sagittarius', 'zodiac'] },
    { emoji: '♑', name: 'capricorn', category: 'Symbols', keywords: ['capricorn', 'zodiac'] },
    { emoji: '♒', name: 'aquarius', category: 'Symbols', keywords: ['aquarius', 'zodiac'] },
    { emoji: '♓', name: 'pisces', category: 'Symbols', keywords: ['pisces', 'zodiac'] },
    { emoji: '🆔', name: 'id button', category: 'Symbols', keywords: ['id', 'button'] },
    { emoji: '⚛️', name: 'atom symbol', category: 'Symbols', keywords: ['atom', 'symbol', 'science'] },
    { emoji: '🉑', name: 'japanese "acceptable" button', category: 'Symbols', keywords: ['japanese', 'acceptable'] },
    { emoji: '☢️', name: 'radioactive', category: 'Symbols', keywords: ['radioactive', 'nuclear'] },
    { emoji: '☣️', name: 'biohazard', category: 'Symbols', keywords: ['biohazard', 'danger'] },
    { emoji: '📴', name: 'mobile phone off', category: 'Symbols', keywords: ['mobile', 'phone', 'off'] },
    { emoji: '📳', name: 'vibration mode', category: 'Symbols', keywords: ['vibration', 'mode'] },
    { emoji: '🈶', name: 'japanese "not free of charge" button', category: 'Symbols', keywords: ['japanese', 'not', 'free'] },
    { emoji: '🈚', name: 'japanese "free of charge" button', category: 'Symbols', keywords: ['japanese', 'free'] },
    { emoji: '🈸', name: 'japanese "application" button', category: 'Symbols', keywords: ['japanese', 'application'] },
    { emoji: '🈺', name: 'japanese "open for business" button', category: 'Symbols', keywords: ['japanese', 'open', 'business'] },
    { emoji: '🈷️', name: 'japanese "monthly amount" button', category: 'Symbols', keywords: ['japanese', 'monthly', 'amount'] },
    { emoji: '✴️', name: 'eight-pointed star', category: 'Symbols', keywords: ['eight-pointed', 'star'] },
    { emoji: '🆚', name: 'vs button', category: 'Symbols', keywords: ['vs', 'versus', 'button'] },
    { emoji: '💮', name: 'white flower', category: 'Symbols', keywords: ['white', 'flower'] },
    { emoji: '🉐', name: 'japanese "bargain" button', category: 'Symbols', keywords: ['japanese', 'bargain'] },
    { emoji: '㊙️', name: 'japanese "secret" button', category: 'Symbols', keywords: ['japanese', 'secret'] },
    { emoji: '㊗️', name: 'japanese "congratulations" button', category: 'Symbols', keywords: ['japanese', 'congratulations'] },
    { emoji: '🈴', name: 'japanese "passing grade" button', category: 'Symbols', keywords: ['japanese', 'passing', 'grade'] },
    { emoji: '🈵', name: 'japanese "no vacancy" button', category: 'Symbols', keywords: ['japanese', 'no', 'vacancy'] },
    { emoji: '🈹', name: 'japanese "discount" button', category: 'Symbols', keywords: ['japanese', 'discount'] },
    { emoji: '🈲', name: 'japanese "prohibited" button', category: 'Symbols', keywords: ['japanese', 'prohibited'] },
    { emoji: '🅰️', name: 'a button (blood type)', category: 'Symbols', keywords: ['a', 'button', 'blood', 'type'] },
    { emoji: '🅱️', name: 'b button (blood type)', category: 'Symbols', keywords: ['b', 'button', 'blood', 'type'] },
    { emoji: '🆎', name: 'ab button (blood type)', category: 'Symbols', keywords: ['ab', 'button', 'blood', 'type'] },
    { emoji: '🅾️', name: 'o button (blood type)', category: 'Symbols', keywords: ['o', 'button', 'blood', 'type'] },
    { emoji: '🆑', name: 'cl button', category: 'Symbols', keywords: ['cl', 'button'] },
    { emoji: '🅿️', name: 'p button', category: 'Symbols', keywords: ['p', 'button', 'parking'] },
    { emoji: '🈳', name: 'japanese "vacancy" button', category: 'Symbols', keywords: ['japanese', 'vacancy'] },
    { emoji: '🈂️', name: 'japanese "service charge" button', category: 'Symbols', keywords: ['japanese', 'service', 'charge'] },
    { emoji: '🛂', name: 'passport control', category: 'Symbols', keywords: ['passport', 'control'] },
    { emoji: '🛃', name: 'customs', category: 'Symbols', keywords: ['customs'] },
    { emoji: '🛄', name: 'baggage claim', category: 'Symbols', keywords: ['baggage', 'claim'] },
    { emoji: '🛅', name: 'left luggage', category: 'Symbols', keywords: ['left', 'luggage'] },
    { emoji: '🚾', name: 'water closet', category: 'Symbols', keywords: ['water', 'closet', 'bathroom'] },
    { emoji: '🛗', name: 'elevator', category: 'Symbols', keywords: ['elevator', 'lift'] },
    { emoji: '🚹', name: 'men\'s room', category: 'Symbols', keywords: ['men', 'room', 'bathroom'] },
    { emoji: '🚺', name: 'women\'s room', category: 'Symbols', keywords: ['women', 'room', 'bathroom'] },
    { emoji: '🚻', name: 'restroom', category: 'Symbols', keywords: ['restroom', 'bathroom'] },
    { emoji: '🚼', name: 'baby symbol', category: 'Symbols', keywords: ['baby', 'symbol'] },
    { emoji: '🚭', name: 'no smoking', category: 'Symbols', keywords: ['no', 'smoking'] },
    { emoji: '🛗', name: 'elevator', category: 'Symbols', keywords: ['elevator', 'lift'] },
    { emoji: '♿', name: 'wheelchair symbol', category: 'Symbols', keywords: ['wheelchair', 'accessibility'] },
    { emoji: '🚇', name: 'metro', category: 'Symbols', keywords: ['metro', 'subway'] },
    { emoji: '🛄', name: 'baggage claim', category: 'Symbols', keywords: ['baggage', 'claim'] },
    { emoji: '🛅', name: 'left luggage', category: 'Symbols', keywords: ['left', 'luggage'] },
    { emoji: '⚠️', name: 'warning', category: 'Symbols', keywords: ['warning', 'caution'] },
    { emoji: '🚸', name: 'children crossing', category: 'Symbols', keywords: ['children', 'crossing'] },
    { emoji: '⛔', name: 'no entry', category: 'Symbols', keywords: ['no', 'entry'] },
    { emoji: '🚫', name: 'prohibited', category: 'Symbols', keywords: ['prohibited', 'no'] },
    { emoji: '🚳', name: 'no bicycles', category: 'Symbols', keywords: ['no', 'bicycles'] },
    { emoji: '🚯', name: 'no littering', category: 'Symbols', keywords: ['no', 'littering'] },
    { emoji: '🚱', name: 'non-potable water', category: 'Symbols', keywords: ['non-potable', 'water'] },
    { emoji: '🚷', name: 'no pedestrians', category: 'Symbols', keywords: ['no', 'pedestrians'] },
    { emoji: '📵', name: 'no mobile phones', category: 'Symbols', keywords: ['no', 'mobile', 'phones'] },
    { emoji: '🔞', name: 'no one under eighteen', category: 'Symbols', keywords: ['no', 'under', 'eighteen'] },
    { emoji: '☢️', name: 'radioactive', category: 'Symbols', keywords: ['radioactive', 'nuclear'] },
    { emoji: '☣️', name: 'biohazard', category: 'Symbols', keywords: ['biohazard', 'danger'] },
    { emoji: '⬆️', name: 'up arrow', category: 'Symbols', keywords: ['up', 'arrow', 'direction'] },
    { emoji: '↗️', name: 'up-right arrow', category: 'Symbols', keywords: ['up-right', 'arrow', 'direction'] },
    { emoji: '➡️', name: 'right arrow', category: 'Symbols', keywords: ['right', 'arrow', 'direction'] },
    { emoji: '↘️', name: 'down-right arrow', category: 'Symbols', keywords: ['down-right', 'arrow', 'direction'] },
    { emoji: '⬇️', name: 'down arrow', category: 'Symbols', keywords: ['down', 'arrow', 'direction'] },
    { emoji: '↙️', name: 'down-left arrow', category: 'Symbols', keywords: ['down-left', 'arrow', 'direction'] },
    { emoji: '⬅️', name: 'left arrow', category: 'Symbols', keywords: ['left', 'arrow', 'direction'] },
    { emoji: '↖️', name: 'up-left arrow', category: 'Symbols', keywords: ['up-left', 'arrow', 'direction'] },
    { emoji: '↕️', name: 'up-down arrow', category: 'Symbols', keywords: ['up-down', 'arrow', 'direction'] },
    { emoji: '↔️', name: 'left-right arrow', category: 'Symbols', keywords: ['left-right', 'arrow', 'direction'] },
    { emoji: '↩️', name: 'right arrow curving left', category: 'Symbols', keywords: ['right', 'arrow', 'curving', 'left'] },
    { emoji: '↪️', name: 'left arrow curving right', category: 'Symbols', keywords: ['left', 'arrow', 'curving', 'right'] },
    { emoji: '⤴️', name: 'right arrow curving up', category: 'Symbols', keywords: ['right', 'arrow', 'curving', 'up'] },
    { emoji: '⤵️', name: 'right arrow curving down', category: 'Symbols', keywords: ['right', 'arrow', 'curving', 'down'] },
    { emoji: '🔃', name: 'clockwise vertical arrows', category: 'Symbols', keywords: ['clockwise', 'vertical', 'arrows'] },
    { emoji: '🔄', name: 'counterclockwise arrows button', category: 'Symbols', keywords: ['counterclockwise', 'arrows', 'refresh'] },
    { emoji: '🔙', name: 'back arrow', category: 'Symbols', keywords: ['back', 'arrow'] },
    { emoji: '🔚', name: 'end arrow', category: 'Symbols', keywords: ['end', 'arrow'] },
    { emoji: '🔛', name: 'on! arrow', category: 'Symbols', keywords: ['on', 'arrow'] },
    { emoji: '🔜', name: 'soon arrow', category: 'Symbols', keywords: ['soon', 'arrow'] },
    { emoji: '🔝', name: 'top arrow', category: 'Symbols', keywords: ['top', 'arrow'] },
    { emoji: '🛐', name: 'place of worship', category: 'Symbols', keywords: ['place', 'worship'] },
    { emoji: '⚛️', name: 'atom symbol', category: 'Symbols', keywords: ['atom', 'symbol'] },
    { emoji: '🕉️', name: 'om', category: 'Symbols', keywords: ['om', 'hinduism'] },
    { emoji: '✡️', name: 'star of david', category: 'Symbols', keywords: ['star', 'david'] },
    { emoji: '☸️', name: 'wheel of dharma', category: 'Symbols', keywords: ['wheel', 'dharma'] },
    { emoji: '☯️', name: 'yin yang', category: 'Symbols', keywords: ['yin', 'yang'] },
    { emoji: '✝️', name: 'latin cross', category: 'Symbols', keywords: ['latin', 'cross'] },
    { emoji: '☦️', name: 'orthodox cross', category: 'Symbols', keywords: ['orthodox', 'cross'] },
    { emoji: '☪️', name: 'star and crescent', category: 'Symbols', keywords: ['star', 'crescent'] },
    { emoji: '☮️', name: 'peace symbol', category: 'Symbols', keywords: ['peace', 'symbol'] },
    { emoji: '🕎', name: 'menorah', category: 'Symbols', keywords: ['menorah', 'judaism'] },
    { emoji: '🔯', name: 'dotted six-pointed star', category: 'Symbols', keywords: ['dotted', 'six-pointed', 'star'] },
    { emoji: '♈', name: 'aries', category: 'Symbols', keywords: ['aries', 'zodiac'] },
    { emoji: '♉', name: 'taurus', category: 'Symbols', keywords: ['taurus', 'zodiac'] },
    { emoji: '♊', name: 'gemini', category: 'Symbols', keywords: ['gemini', 'zodiac'] },
    { emoji: '♋', name: 'cancer', category: 'Symbols', keywords: ['cancer', 'zodiac'] },
    { emoji: '♌', name: 'leo', category: 'Symbols', keywords: ['leo', 'zodiac'] },
    { emoji: '♍', name: 'virgo', category: 'Symbols', keywords: ['virgo', 'zodiac'] },
    { emoji: '♎', name: 'libra', category: 'Symbols', keywords: ['libra', 'zodiac'] },
    { emoji: '♏', name: 'scorpio', category: 'Symbols', keywords: ['scorpio', 'zodiac'] },
    { emoji: '♐', name: 'sagittarius', category: 'Symbols', keywords: ['sagittarius', 'zodiac'] },
    { emoji: '♑', name: 'capricorn', category: 'Symbols', keywords: ['capricorn', 'zodiac'] },
    { emoji: '♒', name: 'aquarius', category: 'Symbols', keywords: ['aquarius', 'zodiac'] },
    { emoji: '♓', name: 'pisces', category: 'Symbols', keywords: ['pisces', 'zodiac'] },
    { emoji: '⛎', name: 'ophiuchus', category: 'Symbols', keywords: ['ophiuchus', 'zodiac'] },
    { emoji: '🔀', name: 'twisted rightwards arrows', category: 'Symbols', keywords: ['twisted', 'rightwards', 'arrows', 'shuffle'] },
    { emoji: '🔁', name: 'repeat button', category: 'Symbols', keywords: ['repeat', 'button'] },
    { emoji: '🔂', name: 'repeat single button', category: 'Symbols', keywords: ['repeat', 'single', 'button'] },
    { emoji: '▶️', name: 'play button', category: 'Symbols', keywords: ['play', 'button'] },
    { emoji: '⏩', name: 'fast-forward button', category: 'Symbols', keywords: ['fast-forward', 'button'] },
    { emoji: '⏭️', name: 'next track button', category: 'Symbols', keywords: ['next', 'track', 'button'] },
    { emoji: '⏯️', name: 'play or pause button', category: 'Symbols', keywords: ['play', 'pause', 'button'] },
    { emoji: '◀️', name: 'reverse button', category: 'Symbols', keywords: ['reverse', 'button'] },
    { emoji: '⏪', name: 'fast reverse button', category: 'Symbols', keywords: ['fast', 'reverse', 'button'] },
    { emoji: '⏮️', name: 'last track button', category: 'Symbols', keywords: ['last', 'track', 'button'] },
    { emoji: '🔼', name: 'upwards button', category: 'Symbols', keywords: ['upwards', 'button'] },
    { emoji: '⏫', name: 'fast up button', category: 'Symbols', keywords: ['fast', 'up', 'button'] },
    { emoji: '🔽', name: 'downwards button', category: 'Symbols', keywords: ['downwards', 'button'] },
    { emoji: '⏬', name: 'fast down button', category: 'Symbols', keywords: ['fast', 'down', 'button'] },
    { emoji: '⏸️', name: 'pause button', category: 'Symbols', keywords: ['pause', 'button'] },
    { emoji: '⏹️', name: 'stop button', category: 'Symbols', keywords: ['stop', 'button'] },
    { emoji: '⏺️', name: 'record button', category: 'Symbols', keywords: ['record', 'button'] },
    { emoji: '⏏️', name: 'eject button', category: 'Symbols', keywords: ['eject', 'button'] },
    { emoji: '🎦', name: 'cinema', category: 'Symbols', keywords: ['cinema', 'movie', 'film'] },
    { emoji: '🔅', name: 'dim button', category: 'Symbols', keywords: ['dim', 'button', 'brightness'] },
    { emoji: '🔆', name: 'bright button', category: 'Symbols', keywords: ['bright', 'button', 'brightness'] },
    { emoji: '📶', name: 'antenna bars', category: 'Symbols', keywords: ['antenna', 'bars', 'signal'] },
    { emoji: '📳', name: 'vibration mode', category: 'Symbols', keywords: ['vibration', 'mode'] },
    { emoji: '📴', name: 'mobile phone off', category: 'Symbols', keywords: ['mobile', 'phone', 'off'] },
    { emoji: '♀️', name: 'female sign', category: 'Symbols', keywords: ['female', 'sign', 'woman'] },
    { emoji: '♂️', name: 'male sign', category: 'Symbols', keywords: ['male', 'sign', 'man'] },
    { emoji: '⚧️', name: 'transgender symbol', category: 'Symbols', keywords: ['transgender', 'symbol'] },
    { emoji: '✖️', name: 'multiply', category: 'Symbols', keywords: ['multiply', 'times', 'x'] },
    { emoji: '➕', name: 'plus', category: 'Symbols', keywords: ['plus', 'add'] },
    { emoji: '➖', name: 'minus', category: 'Symbols', keywords: ['minus', 'subtract'] },
    { emoji: '➗', name: 'divide', category: 'Symbols', keywords: ['divide', 'division'] },
    { emoji: '♾️', name: 'infinity', category: 'Symbols', keywords: ['infinity', 'endless'] },
    { emoji: '‼️', name: 'double exclamation mark', category: 'Symbols', keywords: ['double', 'exclamation', 'mark'] },
    { emoji: '⁉️', name: 'exclamation question mark', category: 'Symbols', keywords: ['exclamation', 'question', 'mark'] },
    { emoji: '❓', name: 'question mark', category: 'Symbols', keywords: ['question', 'mark'] },
    { emoji: '❔', name: 'white question mark', category: 'Symbols', keywords: ['white', 'question', 'mark'] },
    { emoji: '❕', name: 'white exclamation mark', category: 'Symbols', keywords: ['white', 'exclamation', 'mark'] },
    { emoji: '❗', name: 'exclamation mark', category: 'Symbols', keywords: ['exclamation', 'mark'] },
    { emoji: '〰️', name: 'wavy dash', category: 'Symbols', keywords: ['wavy', 'dash'] },
    { emoji: '💱', name: 'currency exchange', category: 'Symbols', keywords: ['currency', 'exchange'] },
    { emoji: '💲', name: 'heavy dollar sign', category: 'Symbols', keywords: ['heavy', 'dollar', 'sign'] },
    { emoji: '⚕️', name: 'medical symbol', category: 'Symbols', keywords: ['medical', 'symbol'] },
    { emoji: '♻️', name: 'recycling symbol', category: 'Symbols', keywords: ['recycling', 'symbol'] },
    { emoji: '⚜️', name: 'fleur-de-lis', category: 'Symbols', keywords: ['fleur-de-lis', 'france'] },
    { emoji: '🔱', name: 'trident emblem', category: 'Symbols', keywords: ['trident', 'emblem'] },
    { emoji: '📛', name: 'name badge', category: 'Symbols', keywords: ['name', 'badge'] },
    { emoji: '🔰', name: 'japanese symbol for beginner', category: 'Symbols', keywords: ['japanese', 'beginner'] },
    { emoji: '⭕', name: 'red circle', category: 'Symbols', keywords: ['red', 'circle', 'correct'] },
    { emoji: '✅', name: 'check mark button', category: 'Symbols', keywords: ['check', 'mark', 'button', 'correct'] },
    { emoji: '☑️', name: 'check box with check', category: 'Symbols', keywords: ['check', 'box', 'correct'] },
    { emoji: '✔️', name: 'check mark', category: 'Symbols', keywords: ['check', 'mark', 'correct'] },
    { emoji: '❌', name: 'cross mark', category: 'Symbols', keywords: ['cross', 'mark', 'x', 'wrong'] },
    { emoji: '❎', name: 'cross mark button', category: 'Symbols', keywords: ['cross', 'mark', 'button', 'x'] },
    { emoji: '➰', name: 'curly loop', category: 'Symbols', keywords: ['curly', 'loop'] },
    { emoji: '➿', name: 'double curly loop', category: 'Symbols', keywords: ['double', 'curly', 'loop'] },
    { emoji: '〽️', name: 'part alternation mark', category: 'Symbols', keywords: ['part', 'alternation', 'mark'] },
    { emoji: '✳️', name: 'eight-spoked asterisk', category: 'Symbols', keywords: ['eight-spoked', 'asterisk'] },
    { emoji: '✴️', name: 'eight-pointed star', category: 'Symbols', keywords: ['eight-pointed', 'star'] },
    { emoji: '❇️', name: 'sparkle', category: 'Symbols', keywords: ['sparkle', 'star'] },
    { emoji: '©️', name: 'copyright', category: 'Symbols', keywords: ['copyright'] },
    { emoji: '®️', name: 'registered', category: 'Symbols', keywords: ['registered'] },
    { emoji: '™️', name: 'trade mark', category: 'Symbols', keywords: ['trade', 'mark', 'trademark'] }
];

const CATEGORIES = ['All', 'Faces & People', 'Animals & Nature', 'Food & Drink', 'Activities', 'Travel & Places', 'Objects', 'Symbols'];

export default function EmojiCatalogue({ onSelectEmoji, onClose, isOpen }: EmojiCatalogueProps) {
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedCategory, setSelectedCategory] = useState('All');

    const filteredEmojis = useMemo(() => {
        let emojis = EMOJI_DATA;

        // Filter by category
        if (selectedCategory !== 'All') {
            emojis = emojis.filter(emoji => emoji.category === selectedCategory);
        }

        // Filter by search term
        if (searchTerm.trim()) {
            const search = searchTerm.toLowerCase();
            emojis = emojis.filter(emoji =>
                emoji.name.toLowerCase().includes(search) ||
                emoji.keywords.some(keyword => keyword.toLowerCase().includes(search)) ||
                emoji.emoji.includes(search)
            );
        }

        return emojis;
    }, [searchTerm, selectedCategory]);

    const handleEmojiClick = (emoji: string) => {
        onSelectEmoji(emoji);
        onClose();
    };

    const clearSearch = () => {
        setSearchTerm('');
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
            <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl h-[80vh] flex flex-col mx-4">
                {/* Header */}
                <div className="flex items-center justify-between p-4 border-b border-gray-200">
                    <h2 className="text-xl font-semibold text-gray-900">Emoji Catalogue</h2>
                    <button
                        onClick={onClose}
                        className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
                    >
                        <XIcon size={20} />
                    </button>
                </div>

                {/* Search */}
                <div className="p-4 border-b border-gray-200">
                    <div className="relative">
                        <MagnifyingGlassIcon size={20} className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                        <input
                            type="text"
                            className="w-full pl-10 pr-10 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="Search emojis by name or keyword..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                        />
                        {searchTerm && (
                            <button
                                onClick={clearSearch}
                                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                            >
                                <XIcon size={16} />
                            </button>
                        )}
                    </div>
                </div>

                {/* Categories */}
                <div className="p-4 border-b border-gray-200">
                    <div className="flex flex-wrap gap-2">
                        {CATEGORIES.map((category) => (
                            <button
                                key={category}
                                onClick={() => setSelectedCategory(category)}
                                className={`px-3 py-2 text-sm rounded-lg transition-colors ${
                                    selectedCategory === category
                                        ? 'bg-blue-600 text-white'
                                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                                }`}
                            >
                                {category}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Emoji Grid */}
                <div className="flex-1 overflow-y-auto p-4">
                    {filteredEmojis.length > 0 ? (
                        <div className="grid grid-cols-8 sm:grid-cols-10 md:grid-cols-12 lg:grid-cols-14 gap-2">
                            {filteredEmojis.map((emojiItem, index) => (
                                <button
                                    key={index}
                                    onClick={() => handleEmojiClick(emojiItem.emoji)}
                                    className="aspect-square flex items-center justify-center text-2xl hover:bg-gray-100 rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-blue-50"
                                    title={emojiItem.name}
                                >
                                    {emojiItem.emoji}
                                </button>
                            ))}
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-full text-gray-500">
                            <div className="text-6xl mb-4">😔</div>
                            <p className="text-lg font-medium mb-2">No emojis found</p>
                            <p className="text-sm">Try a different search term or category</p>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-gray-200 bg-gray-50 rounded-b-lg">
                    <div className="flex items-center justify-between text-sm text-gray-600">
            <span>
              Showing {filteredEmojis.length} of {EMOJI_DATA.length} emojis
                {selectedCategory !== 'All' && ` in ${selectedCategory}`}
            </span>
                        <span>Click any emoji to add it to your scene</span>
                    </div>
                </div>
            </div>
        </div>
    );
}
