import { AssetDefinition } from './actors';

export const BACKGROUNDS: readonly AssetDefinition[] = [
  { id: 'tree', emoji: '🌳', scale: 3, description: 'deciduous tree' },
  { id: 'pine', emoji: '🌲', scale: 3.5, description: 'evergreen tree' },
  { id: 'city', emoji: '🏙️', scale: 3.5, description: 'city skyline' },
  { id: 'office', emoji: '🏢', scale: 4, description: 'office building' },
  { id: 'store', emoji: '🏬', scale: 3.5, description: 'department store' },
  { id: 'beach', emoji: '🏖️', scale: 4, description: 'beach with umbrella' },
  { id: 'palm', emoji: '🌴', scale: 3, description: 'palm tree' },
  { id: 'snowy-mountain', emoji: '🏔️', scale: 4, description: 'snow-capped mountain' },
  { id: 'mountain', emoji: '⛰️', scale: 3, description: 'mountain' },
  { id: 'night-city', emoji: '🌃', scale: 4, description: 'night cityscape' },
  { id: 'moon', emoji: '🌙', scale: 2.5, description: 'crescent moon' },
  { id: 'milky-way', emoji: '🌌', scale: 4, description: 'milky way galaxy' },
  { id: 'planet', emoji: '🪐', scale: 3, description: 'ringed planet' },
  { id: 'desert', emoji: '🏜️', scale: 4, description: 'desert landscape' },
  { id: 'cactus', emoji: '🌵', scale: 3, description: 'cactus' },
  { id: 'castle', emoji: '🏰', scale: 4, description: 'castle' },
  { id: 'sunrise', emoji: '🌅', scale: 4, description: 'sunrise over mountains' },
  { id: 'sunset', emoji: '🌇', scale: 4, description: 'sunset cityscape' },
  { id: 'bridge', emoji: '🌉', scale: 3.5, description: 'bridge at night' },
  { id: 'rainbow', emoji: '🌈', scale: 4, description: 'rainbow' },
  { id: 'park', emoji: '🏞️', scale: 4, description: 'national park' },
  { id: 'camp', emoji: '🏕️', scale: 4, description: 'campground' },
  { id: 'volcano', emoji: '🌋', scale: 4, description: 'volcano' },
  { id: 'island', emoji: '🏝️', scale: 4, description: 'desert island' },
  { id: 'ocean', emoji: '🌊', scale: 4, description: 'ocean wave' },
  { id: 'factory', emoji: '🏭', scale: 4, description: 'factory' },
  { id: 'school', emoji: '🏫', scale: 4, description: 'school' },
  { id: 'hospital', emoji: '🏥', scale: 4, description: 'hospital' },
  { id: 'church', emoji: '⛪', scale: 4, description: 'church' },
  { id: 'stadium', emoji: '🏟️', scale: 4, description: 'stadium' },
];
